const {test}=require('node:test'),assert=require('node:assert/strict'),M=require('./model.js');
test('Wiederholung führt die gesamte Gruppe aus und liefert jede Zustandsänderung',()=>{const r=M.run('wiederhole 3 [\nnimm\nmarkiere\nlege\n]',3);assert.equal(r.trace.length,10);assert.deepEqual(r.end.output,[true,true,true]);assert.equal(r.end.slot,null);assert.equal(r.trace[4].iteration,2);assert.equal(r.trace[4].command,'nimm');assert.equal(r.trace[4].remaining,1);assert.equal(r.trace[4].output.length,1);assert.equal(r.trace[4].line,2);});
test('Falsche Gruppierung stoppt beim zweiten Aufnehmen und verändert den Zustand nicht',()=>{const r=M.run('wiederhole 3 [nimm]\nwiederhole 3 [markiere]\nwiederhole 3 [lege]',3);assert.equal(r.error.step,2);assert.match(r.error.message,/belegt/);assert.equal(r.trace.length,2);assert.equal(r.end.remaining,2);});
test('Markieren ohne Karte stoppt, unmarkiert ablegen bleibt erlaubt',()=>{assert.match(M.run('markiere',3).error.message,/keine Karte/);assert.deepEqual(M.run('nimm lege',3).end.output,[false]);});
test('Einzelbefehl außerhalb der Schleife bleibt einmalig; Reihenfolge ist Teil des Auftrags',()=>{const a=M.run('nimm lege wiederhole 3 [nimm markiere lege]',4);assert.deepEqual(a.end.output,[false,true,true,true]);const b=M.run('wiederhole 3 [nimm markiere lege] nimm lege',4);assert.deepEqual(b.end.output,[true,true,true,false]);assert.equal(a.trace.length,12);});
test('Vorrat und beendeter Code sind unterscheidbar',()=>{assert.match(M.run('wiederhole 4 [nimm markiere lege]',3).error.message,/Vorrat/);assert.deepEqual(M.run('nimm',3).end.slot,{marked:false});});
test('Ungültiger Code wird vollständig vor Ausführung abgelehnt',()=>{for(const code of ['','nimm;','wiederhole 0 [nimm]','wiederhole 10 [nimm]','wiederhole 2 []','wiederhole 2 [wiederhole 2 [nimm]]','nimm alert(1)','wiederhole 2 [nimm'])assert.throws(()=>M.run(code,3));assert.throws(()=>M.run('nimm '.repeat(121),9));assert.throws(()=>M.run('nimm',0));});

test('Einzelschritt zeigt den Stopp erst beim Versuch des unerlaubten Befehls',()=>{const r=M.run('nimm nimm',3);const a=M.advance(r,0);assert.deepEqual(a,{cursor:1,stopped:false});assert.deepEqual(M.advance(r,a.cursor),{cursor:1,stopped:true});assert.deepEqual(M.advance(r,0,true),{cursor:1,stopped:true});assert.deepEqual(M.advance(M.run('markiere',3),0),{cursor:0,stopped:true});});
test('Mehrere Versuche bleiben erhalten; volle Protokolle werden nicht gekürzt',()=>{assert.match(M.appendRecord('Versuch1','Versuch2'),/Versuch2[\s\S]*Versuch1/);assert.throws(()=>M.appendRecord('A'.repeat(9990),'B'.repeat(50)),/nichts ersetzt/);});
