const test=require('node:test'),assert=require('node:assert/strict');
const M=require('./model.js');
function trial(c,moves){let s=M.configure(M.create(),{...c,prediction:'Ich vermute einen Weg.'});s=M.start(s);for(const n of moves)s=M.move(s,n);return s;}
test('V0 request and reply return on selected path',()=>{let s=trial({target:'W'},['A','C','D','W']);assert.equal(M.observe(s.current).phase,'reply');for(let i=0;i<4;i++)s=M.move(s,'reply');assert.equal(s.history[0].prediction,'Ich vermute einen Weg.');assert.equal(M.observe(s.history[0]).outcome,'answered');assert.equal(M.valid(s),true);});
test('V1 selected broken edge fails but another path exists',()=>{let s=trial({disabled:['B-D']},['A','B','D']);assert.equal(M.observe(s.history[0]).outcome,'blocked');assert.ok(M.reachable(s.draft).includes('W'));s=M.reset(s);assert.equal(s.history.length,1);});
test('V3 outside unreachable but local reachable; endpoints do not relay',()=>{const c={disabled:['A-B','A-C'],target:'W',service:true};assert.deepEqual(M.reachable(c).sort(),['A','K','L']);assert.equal(M.neighbors('L').length,1);});
test('service absence and path failure differ',()=>{const s=trial({service:false},['A','C','D','W']);assert.equal(M.observe(s.history[0]).outcome,'no-service');assert.ok(M.reachable(s.draft).includes('W'));});
test('prediction required and trial settings frozen',()=>{assert.throws(()=>M.start(M.create()));const s=M.start(M.configure(M.create(),{prediction:'Vielleicht W.'}));assert.throws(()=>M.configure(s,{target:'L'}));assert.equal(s.current.config.target,'W');});
test('protocol roundtrip, corruption and future versions rejected',()=>{let s=trial({},['A']);assert.ok(M.valid(JSON.parse(JSON.stringify(s))));s.current.moves.push('W');assert.equal(M.valid(s),false);assert.equal(M.valid({...M.create(),version:2}),false);});
test('transfer graph retains first cut and requires changed local route',()=>{assert.ok(M.reachable({disabled:['X-Y']},'transfer').includes('L'));assert.deepEqual(M.reachable({disabled:['X-Y','X-Z']},'transfer').sort(),['K','X']);});
test('stop is an unfinished investigation, not proof of unreachable target',()=>{let s=trial({},['A']);s=M.stop(s);assert.equal(M.observe(s.history[0]).outcome,'stopped');assert.ok(M.reachable(s.draft).includes('W'));});
test('active configuration must match draft; no running trial after full history',()=>{const s=M.start(M.configure(M.create(),{prediction:'Ein Weg.'}));s.draft.target='L';assert.equal(M.valid(s),false);const t=trial({},['A','stop']);const full={...M.start(M.configure(M.create(),{prediction:'Ein Weg.'})),history:Array(50).fill(t.history[0])};assert.equal(M.valid(full),false);});
