'use strict';
(()=>{
 const W=Workshop,M=Lesson,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const dir=['oben','rechts','unten','links'],arrows=['↑','→','↓','←'],icons={vor:'↑',links:'↶',rechts:'↷'},key='ium-lernwerkstatt-v1';
 let current=W.lessons.some(l=>l.id===location.hash.slice(1))?location.hash.slice(1):'start',works={},remember=false,timer=null,speed=1200,edit=null,returnFocus=null;
 try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved?.version===1&&saved.works&&typeof saved.works==='object'){works=saved.works;remember=true;}}catch{}
 const l=()=>W.lesson(current);
 function work(){if(!works[current]||typeof works[current]!=='object')works[current]={};const w=works[current];if(typeof w.code!=='string')w.code=l().code||'';if(!Array.isArray(w.sequence))w.sequence=[];if(!w.prediction||typeof w.prediction!=='object')w.prediction={};w.sequence=w.sequence.filter(a=>['vor','links','rechts'].includes(a)).slice(0,20);if(!Number.isInteger(w.step)||w.step<0)w.step=0;return w;}
 function persist(){if(remember)try{localStorage.setItem(key,JSON.stringify({version:1,works}));}catch{$('#announcer').textContent='Auf diesem Gerät konnte der Stand nicht gespeichert werden. Lass die Seite geöffnet.';}}
 function announce(s){$('#announcer').textContent=s;}
 function stop(){clearInterval(timer);timer=null;}
 function go(id){stop();current=id;location.hash=id;render();$('#lesson-title').focus();window.scrollTo({top:0,behavior:'instant'});}
 function initial(){const c=l();return {pos:c.room.start,cleaned:c.prior||[c.room.start[0]+','+c.room.start[1]],action:'Start'};}
 function execution(){const w=work();if(w.executed!==w.code||!w.executed)return null;try{return W.run(current,w.executed);}catch{return null;}}
 function frame(){const r=execution();return r?r.trace[Math.min(work().step,r.trace.length-1)]:initial();}
 function button(a,text,attrs=''){return '<button data-action="'+a+'" '+attrs+'>'+text+'</button>';}
 function program(){
  const w=work(),c=l();let bs;try{bs=W.blocks(w.code);}catch{return '<p>Der gespeicherte Plan konnte nicht gelesen werden. '+button('restore','Aufgabenstart wiederherstellen')+'</p>';}
  if(!bs.length)return '<div class="empty-program"><span aria-hidden="true">↳</span><strong>Dein erster Teilplan</strong><p>Füge unten eine Anweisung oder eine Schleife hinzu.</p></div>';
  return bs.map((b,i)=>'<'+(c.editable?'button':'div')+' class="block '+(b.repeat?'loop-block':'')+'" '+(c.editable?'data-action="edit" data-index="'+i+'" aria-label="Baustein '+(i+1)+' bearbeiten: '+esc(W.code([b]))+'"':'')+'><span class="line-no">'+(i+1)+'</span><span class="block-content">'+(b.repeat?'<span class="loop-heading"><span class="loop-count">'+b.count+' ×</span> <span>wiederhole</span><span class="loop-bracket">[</span></span>':'')+'<span class="block-body">'+b.body.map((a,j)=>'<span class="instruction" data-line="'+(i+1)+'" data-body="'+j+'"><span aria-hidden="true">'+icons[a]+'</span> '+a+'</span>').join('<span class="separator" aria-hidden="true">;</span>')+'</span>'+(b.repeat?'<span class="loop-end" aria-hidden="true">]</span>':'')+'</span>'+(c.editable?'<span class="edit-mark" aria-hidden="true">✎</span>':'')+'</'+(c.editable?'button':'div')+'>').join('');
 }
 const robot='<svg viewBox="0 0 100 100" aria-hidden="true"><path d="M15 67 4 72M85 67 96 72M19 79 12 89M81 79 88 89" stroke="#9d8e67" stroke-width="4" stroke-linecap="round"/><circle cx="50" cy="50" r="43" fill="#103f3c"/><circle cx="50" cy="50" r="36" fill="#297a70" stroke="#6ba69a" stroke-width="2"/><path d="m50 17 12 17H38Z" fill="#fff7d7"/><path d="M26 48a26 26 0 0 1 48 0" fill="none" stroke="#8bc2af" stroke-width="3"/><rect x="29" y="52" width="42" height="17" rx="8.5" fill="#153f3d"/><circle cx="40" cy="60" r="3" fill="#d0edbf"/><circle cx="60" cy="60" r="3" fill="#d0edbf"/><path d="M37 79h26" stroke="#84b5a2" stroke-width="3" stroke-linecap="round"/></svg>';
 function scene(){
  const c=l(),r=c.room;let tiles='';
  for(let y=1;y<=r.height;y++)for(let x=1;x<=r.width;x++)tiles+='<button class="tile" data-action="predict" data-x="'+x+'" data-y="'+y+'" '+(!c.predict?'disabled':'')+'><span class="coordinate">'+x+','+y+'</span><svg class="crumb" viewBox="0 0 70 70" aria-hidden="true"><path d="m22 20 8 3-3 7-8-3Z M43 37l7-2 3 7-6 3Z" fill="#b68548"/><circle cx="25" cy="46" r="3" fill="#c69a63"/><circle cx="45" cy="22" r="2.5" fill="#a7773f"/></svg><span class="clean-dot" aria-hidden="true">✓</span><span class="prediction-dot" aria-hidden="true">?</span></button>';
  return '<div class="scene"><div class="scene-props" aria-hidden="true"><span class="desk"><i></i><i></i><i></i><b>Basteltisch</b></span><span class="plant">✳</span></div><div class="floor-shell" style="--cols:'+r.width+';--rows:'+r.height+'"><div class="floor" role="group" aria-label="Bodenfläche, '+r.width+' Spalten und '+r.height+' Reihen">'+tiles+'</div><svg class="trail" viewBox="0 0 '+r.width*100+' '+r.height*100+'" preserveAspectRatio="none" aria-hidden="true"><polyline points="" /></svg><div class="robot" id="robot">'+robot+'</div></div><div class="scene-label"><span><i class="key-dirty"></i> Krümel</span><span><i class="key-clean"></i> sauber</span><span>▲ Blickrichtung</span></div></div>';
 }
 function prediction(){const c=l(),w=work();if(!c.predict)return '';return '<div class="predict-box"><span class="eyebrow">Erst im Kopf</span><p id="prediction-status">Tippe deine vermutete Endkachel an.</p><div class="directions" role="group" aria-label="Vermutete Blickrichtung">'+dir.map((d,i)=>button('direction',arrows[i]+' '+d,'data-dir="'+i+'" aria-pressed="'+(w.prediction.d===i)+'"')).join('')+'</div>'+button('new-prediction','Neue Vorhersage','class="text-button"')+'</div>';}
 function support(){
  const c=l(),w=work();return '<section class="learning-support" aria-label="Erklären und weiterdenken"><div class="thinking"><span class="eyebrow">Den Gedanken festhalten</span><h2>'+c.question+'</h2>'+(c.sequence?'<div class="sequence-answer"><div class="sequence-strip" id="sequence-strip"></div><div class="sequence-tools">'+['vor','links','rechts'].map(a=>button('sequence',icons[a]+' '+a,'data-command="'+a+'"')).join('')+button('sequence-undo','↶ Zurück')+button('sequence-check','Folge prüfen','class="dark"')+'</div><p id="sequence-feedback" role="status"></p></div>':'')+'<label for="note">Meine Erklärung <span>– auch mündlich oder auf Papier möglich</span></label><textarea id="note" rows="2" maxlength="3000" placeholder="Ich denke …, weil …">'+esc(w.note||'')+'</textarea><p class="small">Deine Erklärung wird nicht automatisch bewertet. Vergleiche sie mit der Lösung oder besprecht sie zu zweit.</p><button data-action="understood" class="text-button" aria-pressed="'+!!w.understood+'">'+(w.understood?'✓ Für mich geklärt':'○ Für mich als geklärt markieren')+'</button></div><div class="reading-support"><details><summary>Das Prinzip verstehen <span>Erklärung & Beispiel</span></summary><div class="prose">'+c.explain+'</div></details><details><summary>Ein Hinweis für den nächsten Schritt</summary><p>'+c.hints[0]+'</p><details><summary>Noch etwas genauer</summary><p>'+c.hints[1]+'</p></details></details><details><summary>Lösung mit Begründung vergleichen</summary><p class="solution">'+esc(c.solution)+'</p></details><a class="reading-link" href="../selbstlernen/read.html" target="_blank" rel="noopener">Das ganze Kapitel lesen ↗</a></div></section>';
 }
 function render(){
  const c=l(),w=work(),i=W.lessons.indexOf(c);
  $('#main').innerHTML='<div class="journey-bar"><button data-action="menu" class="journey-title"><span class="step-bubble">'+String(i+1).padStart(2,'0')+'</span><span>'+c.group+' <small>Station '+(i+1)+' von '+W.lessons.length+'</small></span><span aria-hidden="true">⌄</span></button><div class="journey-dots" aria-label="Stationen">'+W.lessons.map((q,k)=>'<button data-action="go" data-id="'+q.id+'" aria-label="'+(k+1)+': '+q.short+'" '+(q.id===current?'aria-current="step"':'')+' class="'+(works[q.id]?.understood?'done':'')+'">'+(k+1)+'</button>').join('')+'</div></div><div class="lesson-intro"><h1 id="lesson-title" tabindex="-1">'+c.title+'</h1><p>'+c.goal+'</p></div>'+
   (c.station?stationHTML():'<div class="workbench"><section class="program-panel" aria-labelledby="program-title"><div class="panel-heading"><span class="eyebrow">Dein Auftrag</span><button data-action="help" class="help-button">? Hilfe</button></div><p class="task">'+c.task+'</p>'+(current==='start'?'<p class="command-key"><b>↑ vor</b> eine Kachel fahren<br><b>↶ links / ↷ rechts</b> am Ort eine Vierteldrehung aus Sicht des Roboters</p>':'')+'<div class="program-heading"><h2 id="program-title">'+(c.editable?'Dein Programm':'Das Programm')+'</h2><span>'+(c.editable?'Bausteine antippen':'Von oben nach unten')+'</span></div><div id="program" class="program">'+program()+'</div>'+(c.editable?'<div class="palette" aria-label="Baustein hinzufügen">'+['vor','links','rechts'].map(a=>button('add',icons[a]+' '+a,'data-command="'+a+'"')).join('')+button('add-loop','＋ Schleife','class="loop-add"')+'</div><div class="editor-tools">'+button('undo','↶ Änderung zurück','class="text-button" '+(typeof w.undo!=='string'?'disabled':''))+button('text-code','Code ansehen','class="text-button"')+(w.previous?button('compare','Fahrten vergleichen','class="text-button"'):'')+'</div>':'')+prediction()+'</section><section class="simulation" aria-labelledby="room-title"><div class="room-heading"><div><span class="eyebrow">Dein Testgelände</span><h2 id="room-title">'+(current==='switch'?'Der nächste Reihenwechsel':'Am Basteltisch')+'</h2></div><span class="coverage" id="coverage"></span></div>'+scene()+'<div class="observation"><div id="action-label"></div><p id="state-label"></p></div><div class="transport">'+button('back','↶','aria-label="Eine Aktion zurück"')+button('play','▶ Abspielen','class="dark" id="play"')+button('next','Schritt →','id="next"')+button('cycle','Ein Durchlauf','id="cycle"')+'</div><div class="timeline"><label class="sr-only" for="timeline">Fahrt untersuchen</label><input type="range" min="0" max="1" value="0" id="timeline"><span id="step-label">Start</span></div><div class="extra-controls">'+button('reset','↺ Start','class="text-button"')+button('end','Ergebnis ansehen','class="text-button"')+'<label for="speed" class="sr-only">Tempo</label><select id="speed"><option value="1600">Langsam</option><option value="1200" selected>Ruhig</option><option value="600">Zügig</option></select></div><p class="model-note">Startkachel zählt als sauber · Drehen am Ort · Keine Hinderniserkennung</p></section></div>')+
   '<div id="feedback" class="result-feedback" role="status"></div>'+support()+'<nav class="lesson-footer" aria-label="Nächste Station">'+(i?button('go','← '+W.lessons[i-1].short,'data-id="'+W.lessons[i-1].id+'"'):'<span class="small">Arbeite in deinem Tempo. Alle Stationen sind frei.</span>')+(i<W.lessons.length-1?button('go','Weiter: '+W.lessons[i+1].short+' →','class="dark" data-id="'+W.lessons[i+1].id+'"'):button('journal','Mein Lernheft ansehen →','class="dark"'))+'</nav>';
  if(c.station)paintStation();else paint();paintSequence();
 }
 function paint(){
  const c=l(),w=work(),r=execution(),s=frame(),step=r?Math.min(w.step,r.trace.length-1):0,done=r&&step===r.trace.length-1,total=c.room.width*c.room.height;
  $('#coverage').innerHTML='<b>'+s.cleaned.length+'<span> / '+total+'</span></b><small>Kacheln sauber</small>';
  document.querySelectorAll('.tile').forEach(t=>{
   const x=Number(t.dataset.x),y=Number(t.dataset.y),clean=s.cleaned.includes(x+','+y),selected=w.prediction.x===x&&w.prediction.y===y,here=s.pos[0]===x&&s.pos[1]===y;
   t.classList.toggle('clean',clean);t.classList.toggle('predicted',selected);t.classList.toggle('goal',current==='switch'&&x===1&&y===1);
   t.disabled=!c.predict||!!r;t.setAttribute('aria-label','Spalte '+x+', Reihe '+y+', '+(clean?'sauber':'Krümel')+(here?', Roboter blickt '+dir[s.pos[2]]:'')+(selected?', deine Vermutung':''));
   if(c.predict)t.setAttribute('aria-pressed',String(selected));
  });
  const rb=$('#robot');rb.style.left=((s.pos[0]-.5)/c.room.width*100)+'%';rb.style.top=((s.pos[1]-.5)/c.room.height*100)+'%';const oldAngle=Number(rb.dataset.angle??c.room.start[2]*90),target=s.pos[2]*90;const angle=oldAngle+((target-oldAngle+540)%360+360)%360-180;rb.dataset.angle=angle;rb.style.setProperty('--rotation',angle+'deg');rb.classList.toggle('bump',!!s.error);
  $('.trail polyline').setAttribute('points',r?r.trace.slice(0,step+1).map(f=>(f.pos[0]-.5)*100+','+(f.pos[1]-.5)*100).join(' '):'');
  $('#action-label').innerHTML=step?'<strong>'+icons[s.action]+' '+s.action+'</strong><span>'+(s.error?'Wandstopp':s.repeat?'Durchlauf '+s.iteration+' / '+s.count+(s.bodyIndex===s.bodyLength-1?' · Körper fertig':' · im Körper'):'Anweisung '+s.line)+(s.error?' · versucht':' · ausgeführt')+'</span>':'<strong>Bereit für deinen Plan</strong><span>'+ (c.predict?'Vermute zuerst das Ende.':'Prüfe eine Aktion nach der anderen.')+'</span>';
  $('#state-label').textContent='Spalte '+s.pos[0]+' · Reihe '+s.pos[1]+' · Blick '+dir[s.pos[2]]+(r?.trace[step+1]?' · Als Nächstes: '+r.trace[step+1].action:'');
  $('#play').textContent=timer?'Ⅱ Pause':done?'↺ Noch einmal':'▶ Abspielen';$('#next').disabled=!!done;
  $('[data-action="back"]').disabled=!step;$('#cycle').disabled=!!done||!w.code.includes('wiederhole');$('#cycle').hidden=!w.code.includes('wiederhole');
  const slider=$('#timeline');slider.max=r?r.trace.length-1:1;slider.value=step;slider.disabled=!r;$('#step-label').textContent=r?step+' / '+(r.trace.length-1):'Start';$('#speed').value=String(speed);
  document.querySelectorAll('.instruction').forEach(t=>{const active=step&&Number(t.dataset.line)===s.line&&Number(t.dataset.body)===(s.bodyIndex||0);t.classList.toggle('active',!!active);if(active)t.setAttribute('aria-current','true');else t.removeAttribute('aria-current');});
  const active=$('.instruction.active');if(active){const pr=$('#program'),rect=active.getBoundingClientRect(),bounds=pr.getBoundingClientRect();if(rect.top<bounds.top||rect.bottom>bounds.bottom)pr.scrollTop=Math.max(0,pr.scrollTop+rect.top-bounds.top-60);}
  if(c.predict){$('#prediction-status').textContent=w.prediction.x?'Vermutung: ('+w.prediction.x+','+w.prediction.y+'), Blick '+(dir[w.prediction.d]||'noch wählen')+(r?' · festgehalten':''):'Tippe deine vermutete Endkachel an.';document.querySelectorAll('[data-action="direction"]').forEach(b=>{b.disabled=!!r;b.setAttribute('aria-pressed',String(Number(b.dataset.dir)===w.prediction.d));});}
  const fb=$('#feedback');fb.className='result-feedback';
  if(done){
   const a=W.assess(current,w.executed);fb.classList.add(a.ok?'positive':'attention');
   let compare='';if(c.predict){const p=w.prediction;if(p.x&&Number.isInteger(p.d)){const correct=r.end.join() === [p.x,p.y,p.d].join();compare='<p><b>'+(correct?'Deine Vorhersage passt.':'Das Ende unterscheidet sich von deiner Vorhersage.')+'</b> Ergebnis: ('+r.end[0]+','+r.end[1]+'), Blick '+dir[r.end[2]]+'. Geh zur ersten Stelle zurück, die du anders erwartet hast.</p>';}else compare='<p>Du hast ohne vollständige Vorhersage ausprobiert. Mit „Neue Vorhersage“ kannst du einen Vergleich vorbereiten.</p>';}
   fb.innerHTML='<span class="result-icon" aria-hidden="true">'+(a.ok?'✓':'↳')+'</span><div><h2>'+a.title+'</h2><p>'+a.message+'</p>'+compare+'</div>';
  }else if(w.changed){fb.classList.add('attention');fb.innerHTML='<p>Plan geändert. Die Fläche steht wieder am Start. Prüfe deine neue Fassung.</p>';}
  else fb.innerHTML='';
 }
 function startRun(){
  const w=work();if(execution())return true;
  try{W.run(current,w.code);}catch(e){$('#feedback').className='result-feedback attention';$('#feedback').innerHTML='<p>'+esc(e.message)+'</p>';announce(e.message);return false;}
  w.executed=w.code;w.step=0;w.changed=false;persist();return true;
 }
 function stepTo(step){const w=work(),r=execution();if(!r)return;w.step=Math.max(0,Math.min(step,r.trace.length-1));if(w.step===r.trace.length-1)stop();paint();persist();if(!timer)announce($('#state-label').textContent+(w.step===r.trace.length-1?' '+$('#feedback').textContent:''));}
 function changeCode(code){
  stop();const previousRun=execution(),previousFrame=previousRun?.trace[Math.min(work().step,previousRun.trace.length-1)];if(previousFrame)work().previous={code:work().executed,step:work().step,frame:previousFrame,finished:work().step===previousRun.trace.length-1};const focusAction=document.activeElement?.dataset.action,focusCommand=document.activeElement?.dataset.command;const w=work();w.undo=w.code;w.code=code;w.executed=null;w.step=0;w.changed=true;w.understood=false;persist();render();if(focusAction)Array.from(document.querySelectorAll('[data-action]')).find(b=>b.dataset.action===focusAction&&b.dataset.command===focusCommand)?.focus();
 }
 function show(title,html){stop();if(!l().station)paint();returnFocus=document.activeElement;$('#dialog-title').textContent=title;$('#dialog-content').innerHTML=html;$('#dialog').showModal();}
 function close(){$('#dialog').close();if(returnFocus?.isConnected)returnFocus.focus();}
 function editor(index){
  let bs;try{bs=W.blocks(work().code);}catch{announce('Stelle zuerst den Aufgabenstart wieder her.');return;}
  edit={index,block:index<bs.length?structuredClone(bs[index]):{body:['vor'],count:3,repeat:true}};
  show(index<bs.length?'Baustein bearbeiten':'Schleife hinzufügen','');paintEditor();
 }
 function paintEditor(){
  const focused=document.activeElement,focusAction=focused?.dataset.action,focusIndex=focused?.dataset.index,focusCommand=focused?.dataset.command;
  const b=edit.block,bs=W.blocks(work().code);
  $('#dialog-content').innerHTML='<p>'+(b.repeat?'Alles in der Klammer gehört zu einem Durchlauf.':'Wähle die Anweisung für diesen Baustein.')+'</p>'+(b.repeat?'<div class="count-picker">'+button('count-minus','−','aria-label="Ein Durchlauf weniger" '+(b.count<=2?'disabled':''))+'<strong>'+b.count+' Durchläufe</strong>'+button('count-plus','＋','aria-label="Ein Durchlauf mehr" '+(b.count>=9?'disabled':''))+'</div><h3>In der Klammer</h3><p class="small">Tippe eine Anweisung an, um sie zu entfernen. Füge sie in der gewünschten Reihenfolge wieder hinzu.</p><div class="compose-body">'+b.body.map((a,i)=>button('remove-body',icons[a]+' '+a+' ×','data-index="'+i+'" aria-label="Anweisung '+(i+1)+' '+a+' aus Körper entfernen" '+(b.body.length===1?'disabled':''))).join('')+'</div>':'')+'<div class="palette">'+['vor','links','rechts'].map(a=>button('body-add',icons[a]+' '+a,'data-command="'+a+'" '+(b.repeat&&b.body.length>=5?'disabled':''))).join('')+'</div><pre class="code-preview">'+esc(W.code([b]))+'</pre><div class="dialog-buttons">'+button('save-block','Baustein übernehmen','class="dark"')+'</div>'+(edit.index<bs.length?'<div class="block-operations">'+button('move-up','↑ Nach oben',edit.index===0?'disabled':'')+button('move-down','↓ Nach unten',edit.index===bs.length-1?'disabled':'')+button('delete-block','Baustein entfernen')+'</div>':'');
  if(focusAction&&focusAction!=='close'){const choices=Array.from($('#dialog-content').querySelectorAll('button:not(:disabled)'));(choices.find(t=>t.dataset.action===focusAction&&t.dataset.index===focusIndex&&t.dataset.command===focusCommand)||choices.find(t=>t.dataset.action===focusAction)||choices[0])?.focus();}
 }
 function paintSequence(){if(!l().sequence)return;$('#sequence-strip').innerHTML=work().sequence.length?work().sequence.map((a,i)=>'<span><small>'+(i+1)+'</small>'+icons[a]+' '+a+'</span>').join(''):'<span class="empty-sequence">Deine ausgeschriebene Folge …</span>';}
 function stationCode(plan){const token=a=>'<span data-station-command="'+a+'">'+a+'</span>';return plan==='A'?'wiederhole 3 [<br>  '+token('aufnehmen')+';<br>  '+token('prüfen')+';<br>  '+token('ablegen')+'<br>]':['aufnehmen','prüfen','ablegen'].map(a=>'wiederhole 3 ['+token(a)+']').join('<br>');}
 function stationHTML(){
  const w=work();w.stationPlan ||= 'A';return '<div class="workbench transfer"><section class="program-panel"><span class="eyebrow">Dein Auftrag</span><p class="task">'+l().task+'</p><div class="plan-tabs" role="group" aria-label="Stationsplan auswählen">'+button('station-plan','Plan A','data-plan="A" aria-pressed="'+(w.stationPlan==='A')+'"')+button('station-plan','Plan B','data-plan="B" aria-pressed="'+(w.stationPlan==='B')+'"')+'</div><pre class="station-code">'+stationCode(w.stationPlan)+'</pre><p class="small">Beide Pläne enthalten jeden Befehl dreimal. Prüfe, ob die Station jeweils bereit ist.</p></section><section class="simulation station-scene"><div class="room-heading"><h2>Die Prüfstation</h2><span>Ein Platz für ein Werkstück</span></div><div class="conveyor"><div class="stock"><span>▰</span><span>▰</span><span>▰</span><small>Werkstücke</small></div><div class="station-machine"><div class="scanner"></div><span id="workpiece">▰</span><strong id="station-state"></strong></div><div class="output"><strong id="station-output">0</strong><small>fertig geprüft</small></div></div><p id="station-action" class="station-action"></p><div class="transport">'+button('station-back','↶ Zurück')+button('station-next','Nächste Aktion →','class="dark"')+button('station-reset','↺ Start')+'</div><p class="model-note">aufnehmen: nur wenn frei · prüfen: nur wenn belegt · ablegen: nur nach Prüfung</p></section></div>';
 }
 function paintStation(){const w=work(),run=W.station(w.stationPlan||'A');w.stationStep=Math.max(0,Math.min(w.stationStep||0,run.trace.length-1));const s=run.trace[w.stationStep];$('#station-state').textContent=s.state;$('#workpiece').style.visibility=s.state==='frei'?'hidden':'visible';$('.station-machine').classList.toggle('checked',s.state==='geprüft');$('#station-output').textContent=s.completed;const iteration=w.stationStep?(w.stationPlan==='A'?Math.ceil(w.stationStep/3):(w.stationStep-1)%3+1):0;$('#station-action').textContent='Aktion '+w.stationStep+': '+s.action+(iteration?' · Durchlauf '+iteration+' von 3':'')+(s.error?' – kein Platz für ein zweites Werkstück.':'');document.querySelectorAll('[data-station-command]').forEach(t=>t.classList.toggle('active',w.stationStep>0&&t.dataset.stationCommand===s.action));$('[data-action="station-back"]').disabled=!w.stationStep;$('[data-action="station-next"]').disabled=w.stationStep===run.trace.length-1;const fb=$('#feedback');if(s.error||w.stationStep===run.trace.length-1){fb.className='result-feedback '+(s.error?'attention':'positive');fb.innerHTML='<div><h2>'+(s.error?'Die Station ist noch belegt.':'Drei ganze Arbeitsabläufe geschafft.')+'</h2><p>'+(s.error?'Das zweite Aufnehmen kann nicht ausgeführt werden. Vergleiche, wann Plan A den Platz wieder frei macht.':'Nach jedem Ablegen ist Platz für das nächste Werkstück. Vergleiche nun mit Plan B.')+'</p></div>';}else{fb.className='result-feedback';fb.innerHTML='';}persist();}
 document.addEventListener('click',e=>{
  const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,w=work();
  if(a==='go'){close();go(b.dataset.id);}
  else if(a==='menu')show('Dein Lernweg','<p>Du kannst jede Station öffnen. Haken bedeuten: von dir selbst als geklärt markiert.</p><nav class="menu-list">'+W.lessons.map((q,i)=>button('go','<span>'+String(i+1).padStart(2,'0')+'</span><div><small>'+q.group+'</small><strong>'+q.short+'</strong></div><span>'+(works[q.id]?.understood?'✓':'→')+'</span>','data-id="'+q.id+'" '+(current===q.id?'aria-current="step"':''))).join('')+'</nav>');
  else if(a==='close')close();
  else if(a==='versions')show('Fassungen vergleichen','<p>Die Lernwerkstatt verbindet Simulation und Selbstlernen. Die bisherigen Fassungen bleiben zum Vergleich erreichbar.</p><nav class="version-links"><a href="../reinigungsfall-v2/index.html">Lernfassung 2</a><a href="../selbstlernen/index.html">Selbstlernstrecke</a><a href="../lernfassung-3/index.html">Bisherige Lernfassung 3</a><strong>Lernwerkstatt · diese Fassung</strong><a href="../lernstudio/index.html">Lernstudio · neue Fassung auf Forschungsgrundlage</a></nav>');
  else if(a==='help')show('Hilfe: '+l().short,'<p>'+l().hints[0]+'</p><details><summary>Noch etwas genauer</summary><p>'+l().hints[1]+'</p></details><div class="prose">'+l().explain+'</div>');
  else if(a==='journal')show('Mein Lernheft','<p>Deine Pläne und Gedanken bleiben beim Wechsel zwischen Stationen erhalten.</p><label class="remember"><input id="remember" type="checkbox" '+(remember?'checked':'')+'> Auf diesem Gerät auch nach dem Schließen merken</label><p class="small">Auf einem geteilten iPad ausgeschaltet lassen. Ohne diese Option bleibt der Stand nur, solange diese Seite geöffnet ist. Notizen können auch auf Papier stehen.</p>'+W.lessons.filter(q=>works[q.id]?.note||works[q.id]?.understood||q.id==='own'&&works[q.id]?.code).map(q=>'<article class="journal-entry"><h3>'+q.short+(works[q.id].understood?' · selbst geklärt':'')+'</h3>'+(q.id==='own'?'<pre>'+esc(works[q.id].code||'')+'</pre>':'')+'<p>'+esc(works[q.id].note||'Noch keine schriftliche Erklärung.').replaceAll('\n','<br>')+'</p></article>').join('')+'<p>Zur nächsten Lernzeit: Öffne „Nach einer Pause“ und löse zuerst die neue Aufgabe aus dem Gedächtnis.</p>');
  else if(a==='predict'){w.prediction.x=Number(b.dataset.x);w.prediction.y=Number(b.dataset.y);paint();persist();}
  else if(a==='direction'){w.prediction.d=Number(b.dataset.dir);paint();persist();}
  else if(a==='new-prediction'){stop();w.executed=null;w.step=0;w.prediction={};paint();persist();}
  else if(a==='play'){if(timer){stop();paint();return;}if(!startRun())return;const r=execution();if(w.step>=r.trace.length-1)w.step=0;timer=setInterval(()=>stepTo(work().step+1),speed);paint();}
  else if(['next','back','end','cycle','reset'].includes(a)){stop();if(a==='reset'){w.step=0;paint();persist();return;}if(!startRun())return;const r=execution();let n=w.step+(a==='back'?-1:1);if(a==='end')n=r.trace.length-1;if(a==='cycle'){while(n<r.trace.length-1&&r.trace[n].repeat&&r.trace[n].bodyIndex!==r.trace[n].bodyLength-1)n++;}stepTo(n);}
  else if(a==='edit')editor(Number(b.dataset.index));
  else if(a==='add'){const bs=W.blocks(w.code);if(bs.length>=30){announce('Prüfe erst einen Teilplan: höchstens 30 Bausteine.');return;}changeCode(W.code([...bs,{body:[b.dataset.command],count:1,repeat:false}]));}
  else if(a==='add-loop'){const bs=W.blocks(w.code);if(bs.length<30)editor(bs.length);else announce('Höchstens 30 Bausteine. Prüfe einen Teilplan.');}
  else if(a==='count-minus'||a==='count-plus'){edit.block.count+=a==='count-plus'?1:-1;paintEditor();}
  else if(a==='body-add'){if(edit.block.repeat)edit.block.body.push(b.dataset.command);else edit.block.body=[b.dataset.command];paintEditor();}
  else if(a==='remove-body'){edit.block.body.splice(Number(b.dataset.index),1);paintEditor();}
  else if(['save-block','delete-block','move-up','move-down'].includes(a)){const bs=W.blocks(w.code),i=edit.index;if(a==='save-block')bs.splice(i,1,edit.block);else if(a==='delete-block')bs.splice(i,1);else{bs[i]=edit.block;const j=i+(a==='move-up'?-1:1);[bs[i],bs[j]]=[bs[j],bs[i]];}close();changeCode(W.code(bs));const focusIndex=Math.max(0,Math.min(i+(a==='move-up'?-1:a==='move-down'?1:0),bs.length-1));$('#program').querySelector('[data-index="'+focusIndex+'"]')?.focus();}
  else if(a==='undo'){if(typeof w.undo==='string'){const previous=w.undo;changeCode(previous);}}
  else if(a==='restore')changeCode(l().code||'');
  else if(a==='compare'){const old=w.previous,r=execution(),now=r?frame():null;const card=(title,code,f,step,finished)=>'<article class="comparison-card"><h3>'+title+'</h3><pre class="code-preview">'+esc(code)+'</pre><p>'+(f?'Aktion '+step+(finished?' · Fahrt beendet':' · Zwischenstand')+'<br>'+f.cleaned.length+' Kacheln sauber · Ort ('+f.pos[0]+','+f.pos[1]+'), Blick '+dir[f.pos[2]]:'Noch nicht ausgeführt.')+'</p></article>';show('Was hat deine Änderung bewirkt?','<div class="comparison">'+card('Vor der Änderung',old.code,old.frame,old.step,old.finished)+card('Dein aktueller Plan',w.code,now,w.step,!!r&&w.step===r.trace.length-1)+'</div><p>Vergleiche dieselbe Stelle in beiden Plänen. Erkläre, welche Änderung die Abweichung verursacht hat.</p>');}
  else if(a==='text-code')show('Dein Programm als Code','<pre class="code-preview">'+esc(w.code||'Noch keine Bausteine.')+'</pre><p>Die Bausteine und dieser Code beschreiben genau denselben Plan.</p>');
  else if(a==='sequence'){if(w.sequence.length<20)w.sequence.push(b.dataset.command);paintSequence();$('#sequence-feedback').textContent='';persist();}
  else if(a==='sequence-undo'){w.sequence.pop();paintSequence();$('#sequence-feedback').textContent='';persist();}
  else if(a==='sequence-check'){const expected=l().sequence;let i=expected.findIndex((v,i)=>v!==w.sequence[i]);$('#sequence-feedback').textContent=i<0&&expected.length===w.sequence.length?'Die Folge passt. Erkläre jetzt, wo ein Durchlauf endet.':i<0?'Deine Folge enthält noch zusätzliche Anweisungen.': 'Vergleiche Anweisung '+(i+1)+': Geh den Körper in seiner Reihenfolge durch. Ein Durchlauf endet erst nach der letzten Anweisung in der Klammer.';}
  else if(a==='understood'){w.understood=!w.understood;persist();b.textContent=w.understood?'✓ Für mich geklärt':'○ Für mich als geklärt markieren';b.setAttribute('aria-pressed',String(w.understood));document.querySelectorAll('.journey-dots button').forEach(t=>t.classList.toggle('done',!!works[t.dataset.id]?.understood));}
  else if(a==='station-plan'){w.stationPlan=b.dataset.plan;w.stationStep=0;render();}
  else if(a.startsWith('station-')){w.stationStep=a==='station-reset'?0:(w.stationStep||0)+(a==='station-next'?1:-1);paintStation();announce($('#station-action').textContent+' Station '+$('#station-state').textContent+'. '+$('#station-output').textContent+' fertig geprüft.');}
 });
 document.addEventListener('input',e=>{if(e.target.id==='note'){work().note=e.target.value;persist();}else if(e.target.id==='timeline'){stop();stepTo(Number(e.target.value));}});
 document.addEventListener('change',e=>{if(e.target.id==='speed'){speed=Number(e.target.value);if(timer){stop();timer=setInterval(()=>stepTo(work().step+1),speed);}}else if(e.target.id==='remember'){remember=e.target.checked;if(remember)persist();else try{localStorage.removeItem(key);}catch{}}});
 $('#dialog').addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus();});
 window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(id!==current&&W.lessons.some(c=>c.id===id))go(id);});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();if(!l().station)paint();}});
 render();
})();
