// Fachinhalt kommt aus derselben Quelle wie die interaktive Lernseite.
'use strict';
const P=require('../m06-lernstudio/studio-learning.js'),S=require('../m06-lernstudio/studio-model.js'),G=require('../m06-lernstudio/studio-guides.cjs');
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const questions={start:'Was verändert Fahren, was verändert Drehen?',loop:'Was ist ein Schleifenkörper?',after:'Was passiert nach der Schleife?',repair:'Wie finde ich einen Fehler im Ablauf?',example:'Wie helfen Teilpläne?',rows:'Wie viele Fahrten braucht eine Reihe?',switch:'Welche Drehung passt zum Blick?',own:'Wie entwickle ich einen eigenen Algorithmus?',check:'Wann ist ein Plan wirklich vollständig?',transfer:'Gleiche Befehle – gleicher Ablauf?',return:'Wie prüfe ich mein Verständnis nach einer Pause?'};
const purposes={start:'Ort und Blickrichtung unterscheiden.',loop:'Die ganze Befehlsgruppe wiederholen.',after:'Schleifenkörper und nachfolgenden Befehl trennen.',repair:'Einen Fehler finden und begründet verbessern.',example:'Einen Musterweg in drei Teilpläne zerlegen.',rows:'Schleifenzahlen aus der Fläche begründen.',switch:'Eine Drehung aus dem aktuellen Blick ableiten.',own:'Einen eigenen Flächenplan entwickeln und erklären.',check:'Eine Behauptung mit einem Gegenbeispiel prüfen.',transfer:'Das Schleifenprinzip auf eine andere Maschine übertragen.',return:'Befehlsfolge und Endzustand nach einer Pause rekonstruieren.'};
const paperTasks={
start:'Lies vor – links – vor. Markiere die vermutete Endkachel und zeichne einen Pfeil für den Blick. Verfolge danach jeden Befehl mit einer Figur oder dem Finger. Erkläre: Was verändert die Drehung, was bleibt gleich?',
loop:'Schreibe die Befehle für zwei Durchläufe aus. Verfolge danach alle vier Durchläufe auf dem Raster. Markiere jeweils das Ende einer Gruppe. Erkläre, warum vier Durchläufe acht Aktionen ergeben.',
after:'Sage zuerst Endkachel und Blick nach der Schleife voraus, danach nach dem ganzen Programm. Verfolge die Befehle am Raster. Kennzeichne den einzelnen Befehl außerhalb der Klammer und erkläre seine Wirkung.',
repair:'Verfolge den fehlerhaften Plan auf dem Raster bis zum ersten Wandstopp. Ändere ihn so, dass alle vier Kacheln erreicht werden und der Roboter am Start nach rechts blickt. Erkläre, warum deine Änderung die Ursache behebt.',
example:'Zeige die untere Reihe, den Übergang und die obere Reihe im Raster. Ordne jedem Teilweg den passenden Programmteil zu. Erkläre, wozu beide Drehungen im Übergang dienen.',
rows:'Passe beide Schleifenzahlen an die vier Kacheln pro Reihe an. Verfolge deinen Plan auf dem Raster. Alle acht Kacheln sollen ohne Wandstopp erreicht werden. Begründe die beiden Zahlen.',
switch:'Ändere die drei Befehle für den Übergang. Der Roboter soll links oben ankommen und dort nach rechts blicken. Leite jede Drehung aus seinem aktuellen Blick ab. Die übrigen oberen Kacheln sind erst später dran.',
own:'Plane mit dem Finger oder zeichne einen Weg auf dem Raster. Schreibe daraus ein Programm: alle zwölf Kacheln sauber, kein Wandstopp und mindestens eine Schleife. Verfolge deinen Plan Befehl für Befehl. Erkläre seine Teilpläne.',
check:'Prüfe die Behauptung: „Er kommt wieder am Start an. Also ist der ganze Boden sauber.“ Markiere die erreichten Kacheln. Finde die übrigen Krümel und ergänze den Plan. Widerlege die Behauptung mit einem konkreten Gegenbeispiel.',
transfer:'Stelle drei Werkstücke und einen einzigen freien Prüfplatz mit Gegenständen dar. Verfolge Plan A und Plan B. Erkläre, welcher Plan alle drei Werkstücke bearbeitet und wo der andere stoppt.',
return:'Bearbeite diese Aufgabe nach einer Pause zuerst ohne alte Notizen. Schreibe die ganze Folge aus und sage Endkachel und Blick voraus. Verfolge dann jeden Befehl auf dem Raster und begründe dein Ergebnis.'};
function shell(title,body,kind){return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · IuM Lernwerk</title><link rel="stylesheet" href="studio.css"><link rel="stylesheet" href="prototype.css"></head><body class="guide-page ${kind}"><a class="skip" href="#main">Zum Inhalt</a><header class="topbar"><a href="index.html">Lernwerk</a></header><main id="main" tabindex="-1">${body}</main></body></html>`;}
function back(other='material'){return `<nav class="alg-return" aria-label="Zurück und weiter"><a href="index.html" data-lw-return>← Zurück zu deiner Aufgabe</a><a href="${other}.html">${other==='material'?'Unterrichtsmaterial':'Wissen und Beispiele'} →</a></nav>`;}
function example(l){return `<div class="alg-example">${G.start(l)}<div>${G.programs(l)}</div></div>`;}
function knowledge(){
 const topics=S.chapters.map(c=>`<section class="alg-topic"><h3>${e(c.title)}</h3>${c.ids.map(id=>`<a href="#${id}">${e(questions[id])}</a>`).join('')}</section>`).join('');
 const sections=S.order.map(id=>{const l=P.lesson(id);return `<section class="guide-section" id="${id}"><p class="eyebrow">${e(l.group)}</p><h2>${e(questions[id])}</h2><p class="core-sentence"><b>Merke</b> ${l.core}</p>${example(l)}<article>${l.explain}</article><details><summary>Eine mögliche Lösung nachvollziehen</summary><pre>${e(l.solution)}</pre></details><nav class="alg-section-links" aria-label="Weiter zu ${e(l.short)}"><a href="index.html#${id}">Passende Aufgabe öffnen →</a><a href="index.html" data-lw-return>Zu deiner bisherigen Aufgabe</a><a href="#nachschlagen">Zur Übersicht ↑</a></nav></section>`;}).join('');
 // Der gemeinsame Glossartext bleibt eine einzige fachliche Quelle.
 const glossary=G.render(false).match(/<section class="guide-section" id="begriffe">[\s\S]*?<\/section>/)[0];
 return shell('Wissen und Beispiele: Algorithmen',back()+`<header class="alg-heading"><p class="eyebrow">Algorithmen · Nachschlagen</p><h1>Was möchtest du verstehen?</h1><p>Wähle eine Frage. Du findest eine kurze Erklärung und ein Beispiel. Danach kannst du direkt zu deiner Aufgabe zurückkehren.</p></header><div class="alg-topics" id="nachschlagen">${topics}<section class="alg-topic"><h3>Begriffe und Vertiefung</h3><a href="#begriffe">Befehl, Algorithmus, Schleife und Zustand</a><a href="#wege">Zwei gültige Wege vergleichen</a></section></div>${sections}${G.ways()}${glossary}`,'alg-knowledge');
}
function materials(){return shell('Unterrichtsmaterial: Sauber geplant',back('wissen')+`<header class="alg-heading"><p class="eyebrow">Algorithmen · Unterrichtsmaterial</p><h1>Ein Baustein für euren Unterricht.</h1><p>Jedes Blatt enthält das Ausgangsmaterial, einen Auftrag und Prüfkriterien. Es lässt sich im Gespräch oder im Heft bearbeiten. Mögliche Lösungen sind getrennt aufklappbar.</p><p><a href="lehrkraft.html">Hinweise für Lehrpersonen →</a></p></header>`+S.chapters.map(c=>`<section class="alg-material-group"><h2>${e(c.title)}</h2><ol class="alg-material-list">${c.ids.map(id=>{const l=P.lesson(id);return `<li class="alg-material-row"><span class="alg-material-number">${String(S.order.indexOf(id)+1).padStart(2,'0')}</span><div><h3>${e(l.short)}</h3><p>${e(purposes[id])}</p><small>${id==='return'?'Einzeln · späterer Abruf':id==='transfer'?'Mit Gegenständen · Austausch':l.editable?'Eigener Entwurf · Partnerprüfung':'Einzeln oder im Gespräch'} · mit möglicher Lösung</small></div><a class="lw-button secondary" href="baustein-${id}.html">Einzelblatt öffnen</a></li>`;}).join('')}</ol></section>`).join(''),'alg-materials');}
function material(id){const l=P.lesson(id);return shell(l.title,back('wissen')+`<p><a href="material.html">← Alle Unterrichtsbausteine</a></p><header class="alg-heading"><p class="eyebrow">Baustein ${S.order.indexOf(id)+1} · ${e(l.group)}</p><h1>${e(l.title)}</h1><p>${e(purposes[id])}</p></header><p>${l.entry}</p>${example(l)}<p><b>Unser Modell:</b> ${l.station?'Die Prüfstation hat genau einen Platz. Erst Ablegen macht ihn wieder frei.':'Die Startkachel ist bereits sauber. Drehen verändert nur den Blick. Am Rand stoppt der Roboter; er sucht keinen anderen Weg.'}</p><section class="sheet-task"><h2>Dein Auftrag</h2><p>${e(paperTasks[id])}</p></section><p><b>So kannst du anfangen:</b> ${e(l.prompt)}</p><div class="lw-answer-space" aria-label="Platz für deine Erklärung"></div><h2>Eine gute Erklärung zeigt</h2><ul>${l.criteria.map(c=>`<li>${e(c)}</li>`).join('')}</ul><p>Vergleiche deine Erklärung mit den Kriterien. Ergänze oder verbessere sie.</p><details><summary>Erklärung und Beispiel</summary>${l.explain}</details><details><summary>Mögliche Lösung</summary><pre>${e(l.solution)}</pre></details><details><summary>Für Lehrpersonen: Gespräch und Vorbereitung</summary><p>${l.teach}</p><p><b>Gesprächsimpuls:</b> ${l.discuss}</p></details><nav class="alg-section-links"><a href="index.html#${id}">Im Lernwerk ausprobieren →</a><a href="wissen.html#${id}">Passende Erklärung nachlesen</a></nav>`,'alg-sheet');}
module.exports={knowledge,materials,material};
