'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const A=require('./class5-content.cjs'),R=require('./class5-author-render.cjs'),P=require('./mantel-render.cjs'),T=require('./class6-teacher-pages.cjs');
function augment(assets){const packs=A.load(6),units=packs.map(A.unit),created=new Map();const page=(title,body,u=null,f='index.html')=>P.page(title,body,units,u,f).replace('</head>','<link rel="stylesheet" href="'+(u?'../':'')+'klasse6.css"></head>');
for(const pack of packs){const u=units.find(x=>x.id===pack.id);for(const [file,body]of R.render(pack)){let html=page(pack.title,body,u,file).replace('</head>','<link rel="stylesheet" href="netz.css"></head>');if(body.includes('data-net-tool'))html=html.replace('</head>','<script src="netz-view.js" defer></script><script src="netz-app.js" defer></script></head>');created.set(u.area+'/'+file,html);}for(const [out,src]of [['netz.css','style.css'],['netz-view.js','view.js'],['netz-app.js','app.js']])created.set(u.area+'/'+out,fs.readFileSync(path.join(__dirname,'../m01-netze',src),'utf8'));for(const [file,data]of A.assets(pack))created.set(u.area+'/'+file,data);}
created.set('index.html',page('Klasse 6','<section class="lw-hero"><p class="lw-eyebrow">Informatik und Medienbildung · Klasse 6</p><h1>Vermuten. Prüfen.<br>Selbst erklären.</h1><p class="lw-lead">Untersuche, wie Dateien durch ein Netz gelangen, und probiere echte Speicherwege aus.</p></section><section class="lw-card"><p class="lw-eyebrow">01 · Netze und Speicher</p><h2>Welche Verbindung zählt?</h2><p>Du veränderst ein Netz, prüfst eigene Vermutungen und begründest einen Speicherort.</p><a class="lw-button" href="netze/index.html">Lernbogen öffnen →</a></section><p class="lw-small">Weitere Themen folgen. <a href="lehrkraft.html">Für Lehrpersonen: Planung und Erprobung</a></p><p><a href="../klasse5/index.html">Klasse 5 öffnen</a></p>'));
for(const [file,title]of [['wissen.html','Wissen und Beispiele'],['material.html','Unterrichtsmaterial']])created.set(file,page(title,'<p class="lw-eyebrow">Klasse 6</p><h1>'+title+'</h1><p><a class="lw-button" href="netze/'+file+'">Netze und Speicher →</a></p>',null,file));
for(const [file,title,body]of [['lehrkraft.html','Für Lehrpersonen',T.overview()],['stoffverteilung.html','Jahrgangsbrief Klasse 6',T.distribution()],['reihe-m01.html','Reihenkommentar M01',T.series()],['arbeit.html','Deine Arbeit',P.workContent()],['informationen.html','Gut zu wissen','<div class="lw-readable"><h1>Gut zu wissen.</h1><p>Diese Klasse-6-Fassung dient der Sichtung und Erprobung. Eigene Lerntexte, Modelle und Darstellungen: IuM-Lernwerk, CC BY-SA 4.0; eigener Code: MIT. <a href="netze/material.html">Quellen und gesonderte Rechte</a>.</p><p>Antworten und Netzprotokolle bleiben zunächst im Browsertab. Unter „Deine Arbeit“ kannst du auf diesem Gerät speichern oder eine Arbeitsdatei für den Gerätewechsel herunterladen. Prüfe den tatsächlichen Download. Echte Übungsdateien liegen gesondert; die Arbeitsdatei enthält sie nicht.</p><p>Keine Konten, zentrale Lernanalyse oder automatische Bewertung eigener Erklärungen. Vorhandene Arbeitsstände aus Klasse 5 bleiben getrennt in Klasse 5. Hilfen und Vergleichslösungen kannst du öffnen; ein Klick belegt kein Können.</p><p>Die Offlinefunktion bereitet Lernwerkseiten vor. Sie stellt keinen echten Schulnetz- oder Cloudzugang her. Das Netzmodell zeigt mögliche Wege, nicht das Verhalten eines wirklichen Routers. Berechtigungen, aktuelle Serverdateien und die Schulgeräte sind gesondert zu prüfen.</p><p>Bedienung: Tab führt zu Schaltflächen und Feldern, Enter/Leertaste betätigen sie. Wegschritte lassen sich auch antippen. <a href="netze/material.html">Papiermaterial</a> ist ohne gespeicherten Stand nutzbar.</p></div>']])created.set(file,page(title,body,null,file));
for(const name of ['mantel.css','learning-ui.css','identity.css','learning-ui.js','mantel-model.js','mantel-runtime.js'])created.set(name,assets.get('klasse5/'+name));created.set('klasse6.css',fs.readFileSync(path.join(__dirname,'klasse6.css'),'utf8'));for(const size of [192,512])created.set('icon-'+size+'.png',fs.readFileSync(path.join(__dirname,'../../apps/lernwerk-portal/public/icons/pwa-'+size+'x'+size+'.png')));created.set('net-model.js',fs.readFileSync(path.join(__dirname,'../m01-netze/model.js'),'utf8'));
created.set('manifest.webmanifest',JSON.stringify({name:'IuM Lernwerk – Klasse 6',short_name:'Lernwerk 6',lang:'de',start_url:'./',scope:'./',display:'standalone',background_color:'#F7F7F2',theme_color:'#2D52EE',icons:[192,512].map(size=>({src:'icon-'+size+'.png',sizes:size+'x'+size,type:'image/png'}))}));const hash=crypto.createHash('sha256');for(const value of created.values())hash.update(value);created.set('mantel-sw.js',fs.readFileSync(path.join(__dirname,'mantel-sw.js'),'utf8').replace('__VERSION__',hash.digest('hex').slice(0,12)).replace('__FILES__',JSON.stringify([...created.keys()])));for(const [name,value]of created)assets.set('klasse6/'+name,value);return assets;}
module.exports={augment};
