const test=require('node:test'),assert=require('node:assert/strict'),A=require('./class5-content.cjs');
const clone=x=>JSON.parse(JSON.stringify(x));
function fixture(){return {authorVersion:2,area:'datei-probe',id:'IUM-5-M01-PROBE',version:'1.0.0',grade:5,family:'content',title:'Ablage',topic:'Dateien',description:'Dateien wiederfinden.',product:'Eine geordnete Datei',prerequisites:['Ein vereinbarter Speicherort'],teacher:['Geräte prüfen'],curriculum:{moduleId:'G5-M01',goalIds:['3.1.5.1(2)'],source:'plan',scope:'Teilziel'},duration:'90 Minuten als Planungsannahme',sources:[{id:'plan',title:'Quelle',author:'Redaktion',url:'https://example.org/plan',license:'Nur verlinkt',checked:'2026-10-03'}],media:[{id:'bild',kind:'image',file:'assets/dateien/ablage.svg',title:'Ordnerbaum',alt:'Speicherort mit Ordner und Datei',caption:'Schematische Darstellung',creator:'Lernwerk',license:'CC BY-SA 4.0',sourceId:'plan'},{id:'probe',kind:'download',file:'assets/dateien/fundnotiz.txt',title:'Fundnotiz',printText:'FUNDNOTIZ: Eine blaue Trinkflasche liegt im Fundbüro.',creator:'Lernwerk',license:'CC BY-SA 4.0',sourceId:'plan'}],knowledge:[{id:'ordner',title:'Was ist ein Ordner?',paragraphs:['Ein Ordner gruppiert Dateien.'],example:'Ein Projektordner enthält eine Notiz.',boundary:'Das ist ein Modell, kein Bildschirmfoto.',steps:['einstieg'],sources:['plan'],media:['bild']}],coverage:Object.fromEntries(require('./class5-catalog.cjs').functions.map(f=>[f,['einstieg']])),steps:[{id:'einstieg',title:'Ablegen',goal:'Du legst eine Datei ab.',task:'Plane einen Ort.',outcome:'Dein begründeter Ablageort.',criteria:['Ich finde meine Datei wieder.'],knowledge:['ordner'],blocks:[{type:'external',context:'device',id:'weg',title:'Am Gerät arbeiten',text:'Arbeite im vereinbarten Übungsordner.',preparation:'Öffne deinen Übungsbereich.',action:'Lege die Datei ab.',return:'Öffne sie erneut.',prompt:'Dein Weg',media:['probe'],help:[{title:'Ein Hinweis',text:'Prüfe den übergeordneten Ordner.'}],routes:[{title:'iPad',items:['Öffne Dateien.'],sources:['plan']},{title:'Windows',items:['Öffne den Explorer.'],sources:['plan']}],solution:'Ort und Inhalt prüfen.'}]}]};}
test('Autorenpaket trägt lokale Gerätehandlung mit beiden Wegen und Fachwissen',()=>{const p=fixture();assert.doesNotThrow(()=>A.validate(p));const html=A.renderBlocks(p.steps[0],p);assert.match(html,/iPad/);assert.match(html,/Windows/);assert.match(html,/download/);assert.doesNotMatch(html,/Internet nötig/);assert.match(html,/answer-einstieg-weg/);});
test('Ungültige Medienpfade, fehlende Rechte und unbekannte Referenzen stoppen die Aufnahme',()=>{assert.doesNotThrow(()=>A.validate(fixture()));for(const mutate of [p=>p.media[0].file='../secret.txt',p=>p.media[0].file='assets/../../secret.svg',p=>p.media[0].license='',p=>p.knowledge[0].steps=['fremd'],p=>p.knowledge[0].sources=['fremd'],p=>p.steps[0].blocks[0].media=['fehlt'],p=>p.steps[0].blocks[0].routes[0].sources=['fehlt'],p=>p.steps[0].knowledge=['fehlt'],p=>p.sources[0].url='javascript:alert(1)',p=>p.media.push(clone(p.media[0]))]){const p=fixture();mutate(p);assert.throws(()=>A.validate(p));}});
test('Vollständige Ausgaben trennen Wissen von Material und enthalten Kriterien sowie druckbaren Dateitext',()=>{const R=require('./class5-author-render.cjs'),p=fixture();A.validate(p);const pages=R.render(p);const knowledge=pages.get('wissen.html'),material=pages.get('material.html'),sheet=pages.get('baustein-einstieg.html'),step=pages.get('schritt-einstieg.html');assert.match(knowledge,/Ein Ordner gruppiert Dateien/);assert.doesNotMatch(material,/Ein Ordner gruppiert Dateien/);assert.match(knowledge,/id="ordner"/);assert.match(knowledge,/data-lw-return/);assert.match(sheet,/FUNDNOTIZ/);assert.match(sheet,/Ich finde meine Datei wieder/);assert.doesNotMatch(sheet,/<textarea/);assert.match(sheet,/lw-solution/);assert.match(step,/schritt-einstieg.html/);assert.match(step,/Dein Auftrag/);assert.match(step,/lw-step-menu/);});
test('Erstes echtes Paket wird mit Dateien, Wissen, Lehrbrief und vollständigen Einzelmaterialien veröffentlicht',()=>{const pack=A.load().find(p=>p.area==='dateien');assert.ok(pack,'echtes Paket fehlt');const assets=require('../m06-reinigungsfall/build.cjs').prepare();for(const name of ['index.html','wissen.html','material.html','lehrkraft.html','briefing.html'])assert.ok(assets.has('klasse5/dateien/'+name),name);for(const m of pack.media)assert.ok(assets.has('klasse5/dateien/'+m.file),m.file);for(const s of pack.steps){const html=assets.get('klasse5/dateien/baustein-'+s.id+'.html');assert.ok(html,s.id);for(const c of s.criteria)assert.ok(html.includes(A.esc(c)),c);}assert.match(assets.get('klasse5/index.html'),/dateien\/index.html/);assert.doesNotMatch(assets.get('klasse5/index.html'),/Drei Themen/);assert.match(assets.get('klasse5/mantel-sw.js'),/dateien\/assets\/dateien\/fundnotiz.txt/);});

function runtimePage(page,session,{printMode='learner',details=[]}={}){
 const vm=require('node:vm'),fs=require('node:fs'),M=require('./mantel-model.js'),p=A.load().find(p=>p.area==='dateien'),u=A.unit(p),events={},select={value:printMode,addEventListener(){}},back={href:'index.html'};
 const document={currentScript:{src:'https://lernwerk.test/klasse5/mantel-runtime.js'},body:{dataset:{lwArea:'dateien',lwPage:page}},readyState:'complete',getElementById:id=>id==='lw-catalog'?{textContent:JSON.stringify([u])}:id==='lw-print-mode'?select:null,
 querySelectorAll:s=>s==='[data-lw-return]'?[back]:s==='.lw-author .lw-help,.lw-author .lw-solution'?details:[],addEventListener(){}};
 const storage={getItem:k=>session.get(k)||null,setItem:(k,v)=>session.set(k,v)};
 const window={LernwerkMantelModel:M,addEventListener:(e,fn)=>{events[e]=fn;}};
 vm.runInNewContext(fs.readFileSync(require.resolve('./mantel-runtime.js'),'utf8'),{document,window,location:{hash:'',href:'https://lernwerk.test/klasse5/dateien/'+page},URL,TextEncoder,crypto:require('node:crypto').webcrypto,sessionStorage:storage,localStorage:{getItem:()=>null},navigator:{},queueMicrotask,console});
 return {back,events,body:document.body};
}
test('Wissen kehrt auch ohne erste Antwort zum zuletzt geöffneten Inhaltsschritt zurück',()=>{
 const session=new Map();runtimePage('schritt-planen.html',session);const page=runtimePage('wissen.html',session);
 assert.equal(page.back.href,'schritt-planen.html');
 const saved=JSON.parse(session.get('ium-klasse5-mantel-v1'));assert.equal(saved.records.length,0,'Lesen ist kein Lernnachweis');
 runtimePage('schritt-transfer.html',session);assert.equal(runtimePage('material.html',session).back.href,'schritt-transfer.html');
});
test('Drucken trennt Hilfen und Lösungen und stellt danach den Lesestand wieder her',()=>{
 for(const mode of ['learner','helpers','solutions']){
  const help={open:false,classList:{contains:()=>false}},solution={open:true,classList:{contains:()=>true}},page=runtimePage('baustein-ablegen.html',new Map(),{printMode:mode,details:[help,solution]});
  page.events.beforeprint();assert.equal(help.open,mode!=='learner');assert.equal(solution.open,mode==='solutions');assert.equal(page.body.dataset.lwPrint,mode);
  page.events.afterprint();assert.equal(help.open,false);assert.equal(solution.open,true);
 }
});

test('Fehlende Medien und abweichende Drucktexte werden vor der Ausgabe abgewiesen',()=>{
 const p=clone(A.load().find(p=>p.area==='dateien'));p.media.find(m=>m.kind==='download').printText+=' Fremder Text';
 assert.throws(()=>A.assets(p),/Druckinhalt weichen ab/);
 const missing=clone(p);missing.media[0].file='assets/dateien/fehlt.svg';assert.throws(()=>A.assets(missing),/ENOENT/);
});
