/* Klasse-5-Begleitseiten verwenden die Fachinhalte der jeweiligen Prototypen. */
'use strict';
const U=require('./learning-ui.js'),e=U.escape;
const media=require('../m05-medienanalyse/content.js'),quest=require('../m02-quellenquest/content.js');
const G=require('../m05-medienanalyse/guides.cjs'),Q=require('../m02-quellenquest/render.cjs');
const sets={
 medienanalyse:{content:media,title:'Ein Bild – zwei Geschichten',topic:'Bilder und ihre Wirkung',questions:['Was sehe ich – und was vermute ich?','Wie verändern Bildausschnitt und Überschrift die Wirkung?','Was ist belegt, widerlegt oder noch offen?','Wie begründe und verbessere ich meinen Bildbeitrag?','Wann passt eine Überschrift zum Ausschnitt?'],workforms:['Bildgespräch · genauerer Satz','Zwei Vergleiche · Bild und Text','Zuordnen · eine Entscheidung begründen','Eigener Beitrag · Überarbeitung','Neues Bild · eigenes Urteil']},
 quellenquest:{content:quest,title:'Was wird aus unserer Pausenwiese?',topic:'Quellen prüfen',questions:['Wie wird aus einer Nachricht eine Prüffrage?','Welche Quelle hilft bei welcher Frage?','Wann trägt eine Textstelle mein Urteil?','Wie schreibe ich eine sachliche Antwort mit Belegen?','Wie prüfe ich widersprüchliche Nachrichten?'],workforms:['Erste Einschätzung · Prüffrage','Dokumente lesen · Auswahl begründen','Textstellen zuordnen · Urteil erklären','Eigene Antwort · Überarbeitung','Neuer Fall · selbst entscheiden']}
};
function shell(title,body,kind){return '<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(title)+' · IuM Lernwerk</title><link rel="stylesheet" href="style.css"></head><body><a class="skip" href="#main">Zum Inhalt</a><header class="topbar"><a href="index.html">Lernwerk</a></header><main id="main" class="doc lw-reading '+kind+'" tabindex="-1">'+body+'</main></body></html>';}
function heading(label,title,text){return '<header class="lw-reading-heading"><p class="lw-eyebrow">'+e(label)+'</p><h1>'+e(title)+'</h1><p>'+e(text)+'</p></header>';}
function links(id){return '<nav class="lw-reading-links"><a href="index.html#'+id+'">Passende Aufgabe öffnen →</a><a href="index.html" data-lw-return>Zu deiner bisherigen Aufgabe</a><a href="#nachschlagen">Zur Übersicht ↑</a></nav>';}
function knowledge(area){const cfg=sets[area],isMedia=area==='medienanalyse';
 const overview='<div class="lw-question-grid" id="nachschlagen">'+cfg.content.steps.map((s,i)=>'<a href="#'+s.id+'"><span>'+e(s.short)+'</span><b>'+e(cfg.questions[i])+'</b></a>').join('')+'</div>';
 const sections=cfg.content.steps.map((s,i)=>'<section class="lw-knowledge-section" id="'+s.id+'"><p class="lw-eyebrow">'+e(s.short)+'</p><h2>'+e(cfg.questions[i])+'</h2>'+(isMedia?'<p class="lw-core"><b>Merke</b> '+e(s.core)+'</p><p>'+e(s.explanation)+'</p><details><summary>Bildbeispiel und Situationskarte ansehen</summary>'+G.knowledgeMaterial(s)+(s.id==='gestalten'?G.calibration(true):'')+'</details>':Q.info(s)+(s.id==='quellen'?Q.model():'')+'<details><summary>Die Quellen zu diesem Beispiel lesen</summary>'+Q.sources(s.sources)+'</details>'+(s.id==='antwort'?Q.comparison():''))+'<details><summary>Eine mögliche Erklärung nachvollziehen</summary><p>'+e(isMedia?s.example:s.expected)+'</p></details>'+links(s.id)+'</section>').join('');
 const ending=isMedia?'<section class="lw-provenance"><h2>Über die Bilder</h2>'+G.credits+'</section>':'<section class="lw-provenance"><h2>Bei echten Nachrichten</h2><p>Die Fälle und Dokumente hier sind erfunden. Prüfe bei echten Nachrichten zusätzlich, ob sie tatsächlich von der genannten Stelle stammen. Suche die ursprüngliche Mitteilung auf einem bekannten Weg. Briefkopf und Datum allein beweisen keine Verlässlichkeit.</p><p>Eine ältere Quelle kann einen früheren Plan richtig beschreiben. Eine neue Quelle kann ihn ändern. Prüfe, ob es um dasselbe Ereignis geht und ob die Änderung nachvollziehbar ist.</p><p><b>AG:</b> Arbeitsgemeinschaft. <b>Hochbeet:</b> ein mit Erde gefüllter Kasten zum Pflanzen.</p></section>';
 return shell('Wissen: '+cfg.topic,U.back()+heading(cfg.topic+' · Nachschlagen','Was möchtest du verstehen?','Wähle eine Frage. Lies die Erklärung und untersuche bei Bedarf das Beispiel. Danach kehrst du direkt zu deiner Aufgabe zurück.')+overview+sections+ending,'lw-knowledge');
}
function materials(area){const cfg=sets[area];return shell('Material: '+cfg.topic,U.back('wissen')+heading(cfg.topic+' · Unterrichtsmaterial','Ein Baustein für euren Unterricht.','Jedes Blatt enthält das nötige Material, einen Auftrag und Prüfkriterien. Arbeitet im Gespräch, im Heft oder auf Papier. Mögliche Lösungen sind getrennt aufklappbar.')+'<p><a href="lehrkraft.html">Hinweise für Lehrpersonen →</a></p><ol class="lw-material-list">'+cfg.content.steps.map((s,i)=>'<li><span class="lw-material-number">'+String(i+1).padStart(2,'0')+'</span><div><h2>'+e(s.short)+'</h2><p>'+e(s.goal)+'</p><small>'+e(cfg.workforms[i])+'</small></div><a class="lw-button secondary" href="baustein-'+s.id+'.html">Einzelblatt öffnen</a></li>').join('')+'</ol>','lw-materials');}
function material(area,id){const cfg=sets[area],i=cfg.content.steps.findIndex(s=>s.id===id),s=cfg.content.steps[i];if(!s)throw new Error('Unknown material '+id);const isMedia=area==='medienanalyse';
 const work=isMedia?G.materialSection(id,true):(s.id==='quellen'?Q.model():'')+Q.sources(s.sources)+'<section class="lw-paper-task"><h2>Dein Auftrag</h2>'+Q.paperTask(s)+'</section>'+Q.info(s)+'<details><summary>Ein Hinweis</summary><p>'+e(s.help)+'</p></details>';
 const solutions='<details class="lw-solution"><summary>Mögliche Lösung</summary><p>'+e(isMedia?s.example:s.expected)+'</p>'+(isMedia&&['belege','transfer'].includes(id)?'<ul>'+(id==='belege'?media.claims:media.transferClaims).map(c=>'<li><b>'+e(c.text)+'</b> '+e(c.feedback)+'</li>').join('')+'</ul>':'')+(isMedia&&id==='gestalten'?G.calibration(true):'')+'</details>';
 return shell(s.title,U.back('wissen')+'<p><a href="material.html">← Alle Unterrichtsbausteine</a></p>'+heading('Baustein '+(i+1)+' · '+cfg.topic,s.title,s.goal)+'<p class="lw-small">'+e(cfg.workforms[i])+' · Erfundenes Unterrichtsmaterial'+(isMedia?' mit KI-Illustrationen':'')+'.</p>'+((isMedia&&['eindruck','transfer'].includes(id))?'<p class="print-note">Beim Ausdruck das Gesamtbild zunächst abdecken und erst nach dem ersten Urteil ansehen.</p>':'')+work+U.criteria(s.criteria,s.outcome)+solutions+'<nav class="lw-reading-links"><a href="index.html#'+id+'">Im Lernwerk ausprobieren →</a><a href="wissen.html#'+id+'">Passende Erklärung nachlesen</a><a href="lehrkraft.html#'+id+'">Für Lehrpersonen</a></nav>'+(isMedia?'<div class="lw-provenance">'+G.credits+'</div>':''),'lw-sheet materials');
}
function preview(area,unit){
 if(area==='medienanalyse')return '<div class="lw-preview lw-preview-media" data-preview="'+area+'" aria-hidden="true"><img src="medienanalyse/assets/schulfest.png" alt=""><span>Ein Bild. Zwei Geschichten.</span></div>';
 if(area==='quellenquest')return '<div class="lw-preview lw-preview-sources" data-preview="'+area+'" aria-hidden="true"><div><small>KLASSENCHAT</small><p>Die ganze Pausenwiese wird zum Garten?</p></div><div><small>SCHULMITTEILUNG · C2</small><p>Die übrige Wiese bleibt zum Spielen frei.</p></div></div>';
 if(area==='lernstudio')return '<div class="lw-preview lw-preview-code" data-preview="'+area+'" aria-hidden="true"><div class="lw-mini-code"><span>wiederhole <b>4</b> mal</span><code>[ ↑ vor · ↶ links ]</code></div><div class="lw-mini-grid"><span></span><span></span><span>→</span><span></span></div></div>';

 if(area==='geraete')return '<div class="lw-preview lw-preview-device" data-preview="'+area+'" aria-hidden="true"><div class="lw-device-screen"><span class="lw-mini-windowbar"><i></i><i></i><i></i></span><div class="lw-device-apps"><span><b>Aa</b>Schreiben</span><span><b>2 + 3</b>Rechnen</span><span><b>▧</b>Bilder</span></div><div class="lw-device-system">Programme auf deinem Gerät</div></div></div>';
 if(area==='dateien')return '<div class="lw-preview lw-preview-files" data-preview="'+area+'" aria-hidden="true"><div class="lw-folder-card"><div class="lw-folder-title"><i></i>Lernwerk</div><div class="lw-folder-branch"><span class="lw-file-leaf">Notizen</span><span class="lw-file-leaf">Bilder</span><span class="lw-file-leaf lw-file-document">fundnotiz.txt</span></div></div></div>';
 if(area==='speicher-zugang')return '<div class="lw-preview lw-preview-access" data-preview="'+area+'" aria-hidden="true"><div class="lw-access-file"><i class="lw-paper-icon"></i><span>Deine Datei</span></div><div class="lw-access-route"><span></span><b>?</b><span></span></div><div class="lw-access-targets"><div><i class="lw-screen-icon"></i>Auf dem Gerät</div><div><i class="lw-door-icon"></i>Im Schulraum</div></div></div>';
 if(area==='recherche')return '<div class="lw-preview lw-preview-search" data-preview="'+area+'" aria-hidden="true"><div class="lw-search-question"><i class="lw-search-icon"></i>Warum sieht der Mond anders aus?</div><div class="lw-search-sources"><div><b>Q1</b><span></span><span></span><em>Fundstelle</em></div><div><b>Q2</b><span></span><span></span><em>Vergleich</em></div></div></div>';
 const image=unit?.media?.find(m=>m.id===unit.preview&&m.kind==='image');
 return image?'<div class="lw-preview lw-preview-diagram" data-preview="'+e(area)+'" aria-hidden="true"><img src="'+e(area+'/'+image.file)+'" alt=""></div>':'<div class="lw-preview lw-preview-topic" data-preview="'+e(area)+'" aria-hidden="true"><span>Entdecken · Ausprobieren · Erklären</span><b>'+e(unit?.topic||'Dein nächstes Thema')+'</b></div>';
}
function cards(units,target){return '<div class="lw-grid">'+units.map((u,i)=>'<article class="lw-card" data-unit="'+e(u.area)+'">'+preview(u.area,u)+'<div class="lw-card-body"><span class="lw-card-number">'+String(i+1).padStart(2,'0')+' · '+e(u.topic)+'</span><h2>'+e(u.title)+'</h2><p>'+e(u.description)+'</p><p class="lw-card-product"><b>Dein Ergebnis</b> '+e(u.product)+'</p><a class="lw-button" href="'+u.area+'/'+target+'">'+(target==='index.html'?'Lerneinheit öffnen':target==='wissen.html'?'Wissen öffnen':target==='lehrkraft.html'?'Hinweise öffnen':'Material öffnen')+' →</a></div></article>').join('')+'</div>';}
module.exports={knowledge,materials,material,cards};
