const fs=require('node:fs');
const path=require('node:path');
const {pages}=require('./content.cjs');
function render(pageSource=pages){return `<!doctype html>
<html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#134e4a"><title>Mit Schleifen planen · IuM Lernwerk</title><link rel="stylesheet" href="app.css"><script src="cleaning-core.js" defer></script><script src="model.js" defer></script><script src="app.js" defer></script></head>
<body><a class="skip" href="#main">Zum Lerninhalt</a><nav class="version-switch" aria-label="Version auswählen"><span class="version-label">Version</span><a href="../m06-reinigungsfall-v2/index.html">Lernfassung 2</a><span class="version-current" aria-current="true">Selbstlernstrecke</span><a href="../m06-lernfassung3/index.html">Lernfassung 3</a><a href="../m06-lernwerkstatt/index.html">Neue Lernwerkstatt</a></nav><header class="topbar"><a class="brand" href="#start"><span class="brand-icon" aria-hidden="true">↳</span><span>IuM <strong>Lernwerk</strong></span></a><span class="course-label">INFORMATIK · GRUNDLAGEN</span><div class="top-actions"><a href="#knowledge" class="knowledge-link" data-knowledge-target="title-knowledge">Wissen</a><button type="button" class="enhanced" id="open-save">Stand mitnehmen</button><a href="read.html" class="reading-link" target="_blank" rel="noopener">Lesefassung</a><button type="button" class="enhanced quiet" id="print">Drucken</button></div></header>
<div class="shell"><nav class="side" aria-label="Kapitel"><p class="eyebrow">Dein Kapitel</p><p class="course-title">Mit Schleifen<br>planen</p><p class="side-note">Verstehen, ausprobieren<br>und selbst anwenden.</p><ol>${pageSource.map((p,i)=>`<li><a href="#${p.id}" data-nav="${p.id}"><span class="nav-number" aria-hidden="true">${i<7?String(i+1).padStart(2,'0'):'?'}</span>${p.label}</a></li>`).join('')}</ol><p class="side-note">Alle Kapitel sind frei zugänglich.</p></nav>
<main id="main" tabindex="-1"><noscript><p class="notice">Du liest die vollständige Lesefassung. Bearbeite Aufgaben auf Papier und öffne die Lösungen zum Vergleich. Die Ablauftabellen ersetzen die interaktive Fahrt. Speichern und automatische Prüfung benötigen JavaScript.</p></noscript><p id="restore-notice" role="status"></p>${pageSource.map((p,i)=>`<section class="lesson" id="${p.id}" aria-labelledby="title-${p.id}"><div class="chapter-meta"><span>${i<7?'LERNWEG '+String(i+1).padStart(2,'0')+' / 07':'DEIN NACHSCHLAGEWERK'}</span><span>IuM · ab Klasse 5</span></div><h1 id="title-${p.id}" tabindex="-1">${p.title}</h1><p class="lead">${p.intro}</p><div class="lesson-content">${p.html}</div><nav class="page-nav" aria-label="Weiter im Lernweg">${i>0?`<a href="#${pages[i-1].id}">← ${pages[i-1].label}</a>`:'<span></span>'}${i<6?`<a class="next-link" href="#${pages[i+1].id}">Weiter: ${pages[i+1].label} →</a>`:i===6?'<a class="next-link" href="#knowledge">Wissen nachschlagen →</a>':'<button type="button" id="back-from-knowledge" class="enhanced">Zurück zu meiner Lernseite</button>'}</nav></section>`).join('')}<footer>Mit Schleifen planen · IuM Lernwerk · Referenzstrecke<br><span>Arbeite in deinem Tempo. Ein Vergleich hilft dir beim nächsten Versuch.</span></footer></main></div>
<a class="mobile-knowledge" href="#knowledge" data-knowledge-target="title-knowledge">Wissen nachschlagen</a><dialog id="save-dialog" aria-labelledby="save-title"><div class="dialog-top"><h2 id="save-title">Deinen Stand mitnehmen</h2><button type="button" id="close-save" aria-label="Sicherung schließen">×</button></div><p>Die Ausschreibaufgabe, dein freier Raumplan, deine Merkhilfe und die aktuelle Lernseite lassen sich sichern. Die neuen freien Antwortfelder bleiben nur im offenen Tab; halte wichtige Antworten zusätzlich auf Papier fest. Es wird kein Name benötigt. Die Inhalte werden nicht an einen Server gesendet.</p><h3>Als Datei mitnehmen</h3><p>Lade die Datei herunter und öffne sie beim nächsten Mal hier. Das funktioniert auch auf einem anderen Gerät.</p><button type="button" id="export">Sicherungsdatei herunterladen</button><label class="file-label">Sicherungsdatei öffnen<input id="import" type="file" accept=".json,application/json"></label><div id="import-preview" hidden><p id="import-summary"></p><p>Übernehmen ersetzt deine aktuellen Eingaben. Lade sie vorher als Datei herunter, wenn du sie behalten möchtest.</p><button type="button" id="apply-import">Geprüfte Datei übernehmen</button><button type="button" id="cancel-import">Abbrechen</button></div><h3>Auf diesem Gerät behalten</h3><label class="option"><input id="remember" type="checkbox"><span>Meinen Stand in diesem Browser speichern</span></label><p>Auf einem gemeinsam genutzten Gerät ist eine Datei besser. Browserdaten können gelöscht werden. Beim Ausschalten entfernen wir nur die Sicherung dieser Referenzstrecke; deine offenen Eingaben bleiben.</p><p id="save-status" role="status"></p></dialog>
</body></html>`;}
function renderReading(pageSource=pages){return render(pageSource).replace(/href="#plan" data-jump="([^"]+)"/g,(_,id)=>`href="#${id}"`).replace(/href="#knowledge" data-knowledge-target="([^"]+)"/g,(_,id)=>`href="#${id}"`).replace(/<script[^>]*><\/script>/g,'').replace(/<details/g,'<details open').replace(/<textarea[^>]*>[\s\S]*?<\/textarea>/g,'<p class="caption">Auf Papier beantworten.</p>').replace(/<input[^>]*type="number"[^>]*>/g,'<span> ____</span>').replace(/ for="[^"]*"/g,'').replace('<noscript>', '<p class="notice">Lesefassung: Alle Kapitel, Hilfen und Lösungen sind geöffnet. Bearbeite die Aufgaben auf Papier. <a href="index.html">Zur interaktiven Fassung mit Prüfung und Sicherung</a>.</p><noscript>').replace(/<p class="notice">Die neuen Antwortfelder[\s\S]*?<\/p>/,'<p>Schreibe Antworten, Programme und Begründungen auf Papier. Alle Lösungen und vollständigen Abläufe stehen in dieser Lesefassung.</p>').replace('Für eine Pause nutze oben „Stand mitnehmen“. Ohne Sicherung bleiben Eingaben nur bis zum Neuladen in diesem Tab.', 'Notiere Antworten und offene Fragen auf Papier, wenn du später weiterarbeiten möchtest.');}
if(require.main===module){fs.writeFileSync(path.join(__dirname,'index.html'),render());fs.writeFileSync(path.join(__dirname,'read.html'),renderReading());}
module.exports={render,renderReading};
