/* Shared classroom content: fictional scenes, explicitly labelled in every view. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MediaContent=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const scenes={
 festival:{file:'schulfest.png',name:'Schulfest',alt:'Links stehen leere Bänke vor einer leeren Bühne. Rechts arbeiten mehrere Kinder und Erwachsene an zwei Basteltischen im selben Schulhof.',context:['Ort: Schulhof der erfundenen Lindenwegschule.','Zeitpunkt der dargestellten Situation: 15:10 Uhr.','Laut Festprogramm beginnt die Aufführung auf der Bühne um 15:30 Uhr. Die Mitmachstände sind bereits geöffnet.','Wie viele Menschen im Laufe des Tages kommen und wie sie das Fest finden, ist nicht angegeben.']},
 library:{file:'bibliothek.png',name:'Schulbibliothek',alt:'Links stehen drei leere Sessel in einer Leseecke. Rechts sitzen mehrere Kinder mit offenen Büchern an einem Tisch. Eine Erwachsene steht dabei.',context:['Ort: Bibliothek der erfundenen Lindenwegschule.','Dargestellt ist ein einzelner Moment während einer Lesegruppe.','Über andere Tageszeiten und die Lesegewohnheiten aller Kinder liegen keine Angaben vor.']}
};
const steps=[
 {id:'eindruck',short:'Entdecken',title:'Ein Bild. Zwei Geschichten.',eyebrow:'01 · Genau hinsehen',task:'Vergleiche die beiden Beiträge. Welchen Eindruck bekommst du? Nenne eine Bildstelle und ein Wort, die dafür sorgen.',goal:'Du unterscheidest, was du siehst und was du daraus vermutest.',start:'Du brauchst kein Vorwissen. Lies die Überschriften und betrachte die Bildausschnitte.',core:'Eine Beobachtung beschreibt Sichtbares. Eine Vermutung geht darüber hinaus.',explanation:'„Die Bänke sind leer“ beschreibt, was im linken Ausschnitt zu sehen ist. „Niemand besucht das Fest“ ist eine Vermutung über das ganze Fest. Dafür reicht dieser Ausschnitt nicht. Eine Überschrift kann deine Aufmerksamkeit auf einen bestimmten Gedanken lenken.',hints:['Beginne mit „Ich sehe …“. Nenne nur Dinge, die du im Bild zeigen kannst.','Vergleiche „Nichts los“ mit „Gemeinsam kreativ“. Welche Wörter bewerten die Situation?'],example:'Im linken Beitrag sehe ich leere Bänke. Die Wörter „Nichts los“ lassen das ganze Fest leer wirken. Im rechten Beitrag sehe ich Kinder beim Basteln. Daraus kann ich noch nicht schließen, wie voll es auf dem gesamten Fest ist.',prompt:'Kannst du deine Aussage am Bild zeigen – oder brauchst du dafür noch eine Information?',criteria:['Ich nenne etwas Sichtbares.','Ich beschreibe den Eindruck eines Wortes oder Bildausschnitts.','Ich kennzeichne meine Vermutung als Vermutung.']},
 {id:'wirkung',short:'Untersuchen',title:'Was verändert deinen Eindruck?',eyebrow:'02 · Eine Sache verändern',task:'Untersuche zuerst den Bildausschnitt, dann die Überschrift. Beschreibe jeweils, was sich am Eindruck verändert.',goal:'Du erklärst die Wirkung von Ausschnitt und Überschrift getrennt.',start:'Ein Bildausschnitt zeigt nur einen Teil eines Bildes. Mit den Tasten oder Reglern wählst du diesen Teil aus.',core:'Verändere eine Sache und halte die andere gleich. So kannst du die Wirkung besser untersuchen.',explanation:'Der Ausschnitt entscheidet, was sichtbar ist und was fehlt. Eine enge Ansicht der Bänke lässt die Basteltische weg. Eine enge Ansicht der Tische lässt die Bänke weg. Die Überschrift lenkt die Deutung zusätzlich. Auch eine freundliche Überschrift kann mehr behaupten, als das Bild belegt. Menschen können auf denselben Beitrag unterschiedlich reagieren.',hints:['Wähle einmal „Bänke“ und einmal „Mitmachstände“. Die Überschrift bleibt dabei gleich. Was fehlt jeweils?','Wechsle dann zu „Nur Überschrift“. Nun bleibt das Bild gleich. Welche Aussage ist besonders weitreichend?'],example:'Beim Ausschnitt „Bänke“ sehe ich keine Menschen. Das kann leer wirken, obwohl rechts im ganzen Bild Kinder basteln. Mit „Nichts los beim Schulfest!“ wird dieser Eindruck auf das gesamte Fest übertragen. Die Überschrift behauptet damit zu viel.',prompt:'Was hast du verändert? Was blieb gleich? Woran erkennst du die Wirkung?',criteria:['Ich benenne die veränderte Sache.','Ich beschreibe, was sichtbar wird oder welche Wörter wirken.','Ich erkläre eine mögliche Wirkung, ohne sie allen Menschen zu unterstellen.']},
 {id:'belege',short:'Prüfen',title:'Woher weißt du das?',eyebrow:'03 · Aussagen belegen',task:'Nutze das ganze Bild und die Situationskarte. Ordne jeder Aussage zu, worauf du sie stützen kannst.',goal:'Du unterscheidest Bildbeobachtung, Zusatzinformation und nicht belegte Behauptung.',start:'Die Situationskarte liefert Angaben zu unserer erfundenen Geschichte. Diese Angaben kann man nicht einfach im Bild sehen.',core:'Ein größeres Bild zeigt mehr. Es erklärt aber nicht automatisch alles.',explanation:'Die Kinder an den Tischen sind im Bild zu erkennen. Die Anfangszeit der Aufführung steht dagegen nur in der Situationskarte. Ob alle das Fest schön finden, erfahren wir aus keinem der beiden Materialien. In echten Beiträgen müsstest du zusätzlich prüfen, woher Bild und Angaben stammen und ob sie verlässlich sind.',hints:['Suche erst eine konkrete Stelle im Bild. Findest du dort die Information wirklich?','Wenn du sie nicht sehen kannst, lies die Situationskarte. Fehlt sie auch dort, kannst du sie mit unserem Material nicht belegen.'],example:'„Die Aufführung beginnt um 15:30 Uhr“ stütze ich auf das Festprogramm in der Situationskarte. Die leere Bühne allein verrät mir keine Uhrzeit. „Alle haben Spaß“ ist nicht belegt: Gesichtsausdrücke zeigen nicht sicher, wie jeder Mensch sich fühlt.',prompt:'Welche Information ergänzt die Karte? Welche Frage bleibt trotzdem offen?',criteria:['Ich nenne die passende Materialstelle.','Ich verwechsle einen Gesichtsausdruck nicht mit sicherem Wissen über Gefühle.','Ich benenne eine Grenze unseres Wissens.']},
 {id:'gestalten',short:'Gestalten',title:'Dein Beitrag zum Schulfest',eyebrow:'04 · Bewusst gestalten',task:'Gestalte einen kurzen Beitrag für die Schulzeitung. Er soll neugierig machen und durch unser Material gedeckt sein.',goal:'Du verbindest Bildausschnitt und eigenen Text zu einer begründeten Aussage.',start:'Du darfst dich auf einen Teil des Festes konzentrieren. Mache in deinem Text deutlich, was du zeigst.',core:'Ein Ausschnitt darf einen Schwerpunkt setzen. Dein Text muss zu dem passen, was du belegen kannst.',explanation:'Wähle zuerst, worüber dein Beitrag informieren soll. Setze dann einen passenden Ausschnitt und schreibe eine Überschrift sowie eine Bildunterschrift. Die Bildunterschrift kann einen wichtigen Zusammenhang ergänzen. Prüfe Wörter wie „alle“, „niemand“, „immer“ und „überall“ besonders genau. Eine Überarbeitung ist Teil des Gestaltens.',hints:['Entscheide dich für einen Schwerpunkt: Basteln, Bühne vor der Aufführung oder der Unterschied zwischen beiden Bereichen.','Nutze „An den …“, „In diesem Moment …“ oder „Laut Festprogramm …“, wenn du deine Aussage genauer machen möchtest.'],example:'Möglichkeit 1: „Gemeinsam basteln am Mitmachstand“. Bildunterschrift: „Kinder gestalten am Nachmittag Papiersterne. Links sind die Bänke vor der Bühne noch leer.“ Möglichkeit 2 mit Bühnenausschnitt: „Die Bühne wartet auf ihren Auftritt“. Bildunterschrift: „Um 15:10 Uhr sind die Bänke leer. Laut Festprogramm beginnt die Aufführung erst um 15:30 Uhr.“ Beide Beiträge können passen, weil sie ihren Schwerpunkt und Kontext deutlich machen.',prompt:'Welche Aussage möchtest du vermitteln? Welche andere Deutung möchtest du vermeiden?',criteria:['Meine Überschrift passt zum gewählten Ausschnitt.','Meine Bildunterschrift ergänzt einen hilfreichen Zusammenhang.','Meine Aussagen sind durch Bild oder Situationskarte gedeckt.','Ich erkläre, was mein Ausschnitt zeigt und was er weglässt.']},
 {id:'transfer',short:'Übertragen',title:'Gilt das auch für ein anderes Bild?',eyebrow:'05 · Selbst anwenden',task:'Prüfe den Bibliotheksbeitrag „Hier liest doch niemand!“. Formuliere eine genauere Überschrift und begründe sie.',goal:'Du wendest die Unterscheidung von Beobachtung und Behauptung auf einen neuen Fall an.',start:'Der neue Fall zeigt eine Schulbibliothek. Du kannst das ganze Bild und zusätzliche Angaben direkt öffnen.',core:'Frage bei jedem Beitrag: Was sehe ich? Was wird behauptet? Was müsste ich noch wissen?',explanation:'Leere Sessel belegen nur, dass auf diesen Sesseln im gezeigten Moment niemand sitzt. Sie belegen nicht, dass in der Bibliothek niemand liest. Im ganzen Bild sind Kinder mit Büchern am Tisch zu sehen. Auch daraus erfahren wir nicht, wie oft die Bibliothek genutzt wird.',hints:['Achte auf das Wort „niemand“. Wie weit reicht diese Behauptung?','Formuliere eine Überschrift über die leere Leseecke oder über die Lesegruppe. Begrenze deine Aussage auf das, was das Material hergibt.'],example:'„Freie Plätze in der Leseecke“ passt zum engen Ausschnitt. „Gemeinsam lesen am Büchertisch“ passt zum rechten Teil des ganzen Bildes. Die ursprüngliche Behauptung wird durch die lesenden Kinder im ganzen Bild widerlegt. Wie oft alle Kinder lesen, bleibt offen.',prompt:'Welche Information fehlt im Ausschnitt? Was weißt du auch nach dem ganzen Bild noch nicht?',criteria:['Ich erkläre das Problem an der Behauptung „niemand“.','Ich stütze meine neue Überschrift auf eine konkrete Bildstelle.','Ich nenne eine weiterhin offene Frage.']}
];
const claims=[
 {id:'benches',text:'Auf den Bänken vor der Bühne sitzt in diesem Moment niemand.',answer:'image',feedback:'Das ist im Bild zu sehen: Die Bänke vor der Bühne sind leer. Die Aussage bleibt auf diesen Ort und Moment begrenzt.'},
 {id:'time',text:'Die Aufführung beginnt laut Festprogramm um 15:30 Uhr.',answer:'context',feedback:'Diese Zeit steht in der Situationskarte. Eine leere Bühne verrät dir allein nicht, wann eine Aufführung beginnt.'},
 {id:'all',text:'Auf dem ganzen Schulfest ist niemand.',answer:'unknown',feedback:'Das ganze Bild widerspricht der Aussage: An den Tischen sind Kinder und Erwachsene zu sehen. Leere Bänke bedeuten nicht, dass das ganze Fest leer ist.'},
 {id:'feeling',text:'Alle Kinder finden das Fest toll.',answer:'unknown',feedback:'Das ist mit dem Material nicht belegt. Ein Gesichtsausdruck beweist nicht, wie alle Kinder das Fest finden. Dazu bräuchtest du weitere Informationen, zum Beispiel ihre eigenen Aussagen.'}
];
const choices=[{id:'image',label:'Im Bild erkennbar'},{id:'context',label:'Angabe der Situationskarte'},{id:'unknown',label:'So nicht belegbar'}];
const headlines=['Ein Nachmittag auf dem Schulfest','Nichts los beim Schulfest!','Gemeinsam kreativ am Mitmachstand','Alle lieben dieses Schulfest!'];
return {scenes,steps,claims,choices,headlines};
});
