const C=require('./content.js');
const M=require('./model.js');
const e=M.escapeHtml;
function picture(scene,crop=M.presets.full){
 return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="'+M.viewBox(crop)+'" role="img" aria-label="'+e(M.cropDescription(scene,crop))+'"><image href="assets/'+scene.file+'" width="1536" height="1024"/></svg>';
}
function figure(scene){
 return '<figure class="full-figure">'+picture(scene)+'<figcaption>'+e(scene.alt)+'<br>KI-Illustration einer erfundenen Situation.</figcaption></figure>';
}
function card(label,scene,crop,headline){
 return '<article class="story"><div class="story-top"><b>'+e(label)+'</b></div>'+picture(scene,crop)+'<div class="story-copy"><h2>'+e(headline)+'</h2></div></article>';
}
function context(scene){
 return '<aside class="context-card"><h3>Situationskarte · erfundener Fall</h3><ul>'+scene.context.map(s=>'<li>'+e(s)+'</li>').join('')+'</ul></aside>';
}
const credits='<p class="credit">Unterrichtsmaterial: IuM-Lernwerk · eigene Texte und Aufgaben nach der <a href="https://github.com/H4R7W16/ium-lernwerk/blob/main/LICENSE-CONTENT.md">Inhaltslizenz CC BY-SA 4.0</a>. Beide Bilder wurden mit OpenAI Imagegen für diesen Prototyp erzeugt. Sie dokumentieren keine realen Personen, Schulen oder Ereignisse. Die Situationskarten sind ebenfalls erfunden. Die tatsächliche Herkunft eines echten Bildes müsste zusätzlich geprüft werden.</p>';
function shell(title,body,kind){
 return '<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(title)+' · Ein Bild – zwei Geschichten</title><link rel="stylesheet" href="style.css"></head><body><a class="skip" href="#main">Zum Inhalt</a><header class="topbar"><a class="brand" href="index.html#eindruck"><span class="brand-mark" aria-hidden="true">◩</span><span>Lernstudio<small>IuM · Medien verstehen</small></span></a><a href="index.html#eindruck">Zum Lernweg →</a></header><main id="main" class="doc '+kind+'"><p class="eyebrow">Ein Bild – zwei Geschichten · Klasse 5</p><h1>'+e(title)+'</h1><nav class="doc-nav" aria-label="Materialseiten"><a href="wissen.html">Wissen</a><a href="lehrkraft.html">Für Lehrpersonen</a><a href="material.html">Materialbogen</a></nav>'+body+'<section><h2>Über die Materialien</h2>'+credits+'</section></main><footer class="site-footer"><span>Ein Bild – zwei Geschichten · Lernstudio</span><a href="index.html#eindruck">Zum Lernweg</a></footer></body></html>';
}
function renderKnowledge(){
 return shell('Wissen und Beispiele','<p>Hier findest du Erklärungen und mögliche Antworten. Du kannst jeden Abschnitt einzeln lesen.</p><nav class="doc-nav" aria-label="Wissensabschnitte">'+C.steps.map(s=>'<a href="#'+s.id+'">'+e(s.short)+'</a>').join('')+'</nav>'+C.steps.map((s,i)=>'<section id="'+s.id+'"><p class="eyebrow">0'+(i+1)+'</p><h2>'+e(s.title)+'</h2><p class="core"><b>Merke</b>'+e(s.core)+'</p>'+(i===0?figure(C.scenes.festival):i===4?figure(C.scenes.library):'')+'<p>'+e(s.explanation)+'</p>'+(i===2?context(C.scenes.festival):'')+'<div class="guide-example"><h3>Eine mögliche Erklärung</h3><p>'+e(s.example)+'</p></div><h3>Prüfe deine eigene Erklärung</h3><ul>'+s.criteria.map(t=>'<li>'+e(t)+'</li>').join('')+'</ul><a class="no-print" href="index.html#'+s.id+'">Diesen Lernschritt bearbeiten →</a></section>').join(''),'knowledge');
}
const timing=[10,20,15,25,20];
const teacherPrompts=[
 'Zeigen Sie zunächst nur die beiden Beiträge. Lassen Sie Beobachtungen und Deutungen getrennt sammeln. Fragen Sie bei „Da ist niemand“ nach dem Geltungsbereich: auf den Bänken oder auf dem gesamten Fest?',
 'Modellieren Sie einen einzigen Vergleich laut: „Ich ändere jetzt nur den Ausschnitt. Die Überschrift bleibt gleich.“ Die Lernenden erklären anschließend eine andere Variante selbst. Für das Unterrichtsgespräch reichen das ganze Bild und die beiden Ausschnitte auf dem Materialbogen.',
 'Lassen Sie zu einer Antwort eine konkrete Bildstelle oder einen Satz der Karte nennen. Bei „alle finden es toll“ klären Sie, was Gesichtsausdrücke zeigen können und was nicht. Thematisieren Sie: Die Karte gehört zur erfundenen Geschichte und ersetzt keine echte Quellenprüfung.',
 'Lassen Sie erst einen Schwerpunkt wählen, dann Bild und Text gestalten. Ein Bühnenausschnitt ist zulässig, wenn der Text die Aussage auf diesen Bereich begrenzt und fehlenden Kontext ergänzt. Eine schöne Gestaltung allein ist kein fachlicher Nachweis. Rückmeldung: „Welche Stelle belegt diesen Satz?“',
 'Zeigen Sie zunächst den engen Bibliotheksausschnitt. Lassen Sie vor dem ganzen Bild überlegen, welche Information fehlen könnte. Die abschließende Begründung sollte ohne vorgelesene Musterantwort entstehen. Auch nach dem ganzen Bild bleiben Häufigkeit und Beliebtheit des Lesens offen.'
];
function renderTeacher(){
 return shell('Für Lehrpersonen',
 '<p>Ein abgeschlossener Ausschnitt zur Medienanalyse mit einem eigenen Text-Bild-Produkt. Die fünf Schritte können selbstständig bearbeitet oder einzeln im Unterrichtsgespräch und Vortrag übernommen werden.</p>'+
 '<div class="teacher-note"><h2>Fachlicher Kern und Lernnachweis</h2><p>Die Lernenden unterscheiden Beobachtung und Deutung, erklären eine Wirkung von Ausschnitt und Überschrift, belegen Aussagen am Material und überarbeiten einen eigenen Beitrag. Ein zugeordnetes Antwortfeld allein weist diese Fähigkeiten nicht nach.</p><p><b>Nachweis:</b> eigener Beitrag mit begründeter Ausschnitt-/Textwahl sowie eine Erklärung am neuen Bibliotheksfall. Mündliche oder handschriftliche Begründungen sind gleichwertige Bearbeitungswege.</p></div>'+
 '<h2>Unterricht unabhängig von der Anwendung</h2><p>Der <a href="material.html">Materialbogen</a> enthält sämtliche Bilder, Ausschnitte, Situationskarten und Arbeitsaufträge ohne Lösungen. Er kann direkt projiziert oder über die Druckfunktion des Browsers gedruckt werden. Für die Bildauswahl können Lernende einen Ausschnitt auf dem Papier markieren und den Beitrag daneben skizzieren. Diese analoge Bearbeitung übt Medienanalyse und Gestaltung, weist aber noch keine digitale Werkzeugbedienung nach.</p>'+
 '<p><b>Wechsel zwischen Lehr- und Selbstlernweg:</b> Erklären Sie etwa Beobachtung und Deutung gemeinsam, dann starten die Lernenden direkt bei <a href="index.html#wirkung">Untersuchen</a>. Jeder Schritt hat einen eigenen Direktlink und eigene Einstiegshilfe; vorherige Klicks sind nicht erforderlich.</p>'+
 '<p><b>Zeitannahme:</b> etwa 90 Minuten für alle Schritte (10 / 20 / 15 / 25 / 20 Minuten). Das ist eine Planungsannahme, noch keine mit Klasse 5 erprobte Dauer. Als kurze Auswahl eignen sich Einstieg, Aussagenprüfung und eine mündliche Transferbegründung; der eigene Gestaltungsnachweis bleibt dann noch offen.</p>'+
 '<p><b>Voraussetzungen:</b> kurze Überschriften lesen, sichtbare Gegenstände beschreiben. Begriffe werden hier erklärt. Bei Leseschwierigkeiten können Aufträge vorgelesen, Satzanfänge genutzt und Antworten zunächst mündlich formuliert werden.</p>'+
 C.steps.map((s,i)=>'<section id="'+s.id+'"><p class="eyebrow">Schritt '+(i+1)+' · ca. '+timing[i]+' Minuten</p><h2>'+e(s.title)+'</h2><p><b>Ziel:</b> '+e(s.goal)+'</p><p><b>Auftrag:</b> '+e(s.task)+'</p><p><b>Übernahme im Unterricht:</b> '+e(teacherPrompts[i])+'</p><p><b>Gesprächsimpuls:</b> '+e(s.prompt)+'</p><div class="guide-example"><h3>Fachliche Orientierung / mögliche Antwort</h3><p>'+e(s.example)+'</p>'+(i===2?'<ul>'+C.claims.map(c=>'<li><b>'+e(c.text)+'</b> '+e(c.feedback)+'</li>').join('')+'</ul>':'')+'</div><p><b>Beobachtungskriterien:</b></p><ul>'+s.criteria.map(t=>'<li>'+e(t)+'</li>').join('')+'</ul><p><b>Hilfe bei Schwierigkeiten:</b> '+e(s.hints.join(' '))+'</p><a href="index.html#'+s.id+'">Direkt zum Lernschritt →</a> · <a href="material.html#'+s.id+'">Passendes Material →</a></section>').join('')+
 '<section><h2>Typische Fehlvorstellungen</h2><ul><li><b>„Jeder Ausschnitt ist eine Täuschung.“</b> Ein Ausschnitt kann sinnvoll fokussieren. Entscheidend sind Aussage, Kontext und mögliche Auslassungen.</li><li><b>„Das ganze Bild sagt alles.“</b> Es bleibt ein gewählter Moment aus einer bestimmten Perspektive.</li><li><b>„Positiv bedeutet richtig.“</b> Auch „Alle lieben dieses Fest“ geht über die Belege hinaus.</li><li><b>„Ein Haken heißt verstanden.“</b> Die Selbstkontrolle bewertet keine offenen Texte. Fragen Sie nach einer konkreten Begründung.</li></ul><p><b>Einordnung:</b> Dieser Ausschnitt unterstützt die geplanten G5-M04/G5-M05-Ziele zu Form, Inhalt und Wirkungsabsicht. Er bildet weder vollständige Module noch eine umfassende Quellenkritik ab. Das schulinterne Mapping bezieht sich auf die IuM-Anhörungsfassung vom 21.09.2026, nicht auf eine behauptete amtliche Einzeljahrzuordnung.</p></section>','teacher');
}
function lines(){return '<div class="write-lines" aria-label="Platz für deine Antwort"></div>';}
function renderMaterials(){
 const s=C.scenes.festival,l=C.scenes.library;
 return shell('Materialbogen',
 '<p>Bearbeite die Aufträge im Gespräch, auf Papier oder im Heft. Die beiden Geschichten sind erfunden. Die Bilder sind KI-Illustrationen. Es gibt bei den Gestaltungsaufträgen mehrere begründbare Lösungen.</p><p class="no-print">Dieser Bogen funktioniert ohne JavaScript. Die Lösungshinweise stehen getrennt unter „Für Lehrpersonen“ und „Wissen“.</p>'+
 '<section id="eindruck"><h2>1 · Welchen Eindruck bekommst du?</h2><div class="pair">'+card('Beitrag A',s,M.presets.left,'Nichts los beim Schulfest!')+card('Beitrag B',s,M.presets.right,'Gemeinsam kreativ am Mitmachstand')+'</div><p>Beschreibe zuerst nur Sichtbares. Erkläre anschließend, welchen Eindruck ein Ausschnitt und ein Wort bei dir erzeugen.</p><p><b>Satzanfänge:</b> „Ich sehe …“ / „Das wirkt auf mich …, weil …“</p>'+lines()+'</section>'+
 '<section id="wirkung"><h2>2 · Eine Sache verändern</h2>'+figure(s)+'<p><b>Ausschnitt:</b> Decke einmal die linke, einmal die rechte Bildhälfte ab oder markiere zwei Ausschnitte. Nutze jedes Mal dieselbe Überschrift: „Ein Nachmittag auf dem Schulfest“. Was verändert sich?</p><p><b>Überschrift:</b> Betrachte jetzt immer das ganze Bild. Vergleiche „Ein Nachmittag auf dem Schulfest“, „Nichts los beim Schulfest!“ und „Alle lieben dieses Schulfest!“. Welche Wörter lenken deine Deutung?</p><p>Erkläre: „Ich ändere … . … bleibt gleich. Dadurch …“</p>'+lines()+'</section>'+
 '<section id="belege"><h2>3 · Was kannst du belegen?</h2>'+context(s)+'<p>Nutze zusätzlich das ganze Bild auf der vorherigen Seite. Ordne zu: <b>B</b> = im Bild erkennbar; <b>K</b> = Angabe der Situationskarte; <b>N</b> = so nicht belegbar.</p><ol>'+C.claims.map(c=>'<li>___ '+e(c.text)+'</li>').join('')+'</ol><p>Begründe eine Zuordnung. Welche Frage bleibt trotz des ganzen Bildes und der Karte offen?</p>'+lines()+'</section>'+
 '<section id="gestalten"><h2>4 · Dein Beitrag zum Schulfest</h2><p>Gestalte für die Schulzeitung einen eigenen Beitrag, der neugierig macht und durch unser Material gedeckt ist. Markiere deinen Ausschnitt im ganzen Bild oder zeichne ihn grob nach.</p><p><b>Deine Überschrift:</b></p>'+lines()+'<p><b>Deine Bildunterschrift:</b></p>'+lines()+'<p><b>Deine Begründung:</b> „Mein Ausschnitt zeigt … und lässt … weg. Meine Überschrift passt, weil …“</p>'+lines()+'<p><b>Prüfe und überarbeite:</b></p><ul>'+C.steps[3].criteria.map(t=>'<li>□ '+e(t)+'</li>').join('')+'</ul></section>'+
 '<section id="transfer"><h2>5 · Neuer Fall: die Schulbibliothek</h2>'+card('Bibliotheksbeitrag',l,M.presets.left,'Hier liest doch niemand!')+'<p>Was zeigt der Ausschnitt? Was behauptet die Überschrift darüber hinaus? Welche zusätzliche Information brauchst du?</p>'+lines()+'<p>Formuliere eine genauere Überschrift und begründe sie. Du kannst dazu das ganze Bild auf der nächsten Seite nutzen.</p>'+lines()+'</section>'+
 '<section id="bibliothek"><h2>Zum Nachsehen: die ganze Bibliotheksszene</h2>'+figure(l)+context(l)+'<p>Welche Vermutung änderst du nach dem ganzen Bild? Was weißt du trotzdem noch nicht? Erkläre an einer Bildstelle.</p>'+lines()+'</section>','materials');
}
module.exports={renderKnowledge,renderTeacher,renderMaterials};
