import argparse
import json
import os
import tempfile
from pathlib import Path

try:
    from .validate_ium11 import validate_pilot_protocol
except (ImportError, TypeError):
    try:
        from scripts.validate_ium11 import validate_pilot_protocol
    except ImportError:
        from validate_ium11 import validate_pilot_protocol


DEFAULT_OUTPUT = Path("pilot/cockpit/assets/protocol.js")


def _load_json(path):
    with path.open("r", encoding="utf-8") as source:
        return json.load(source)


def compile_cockpit_contract(root):
    root = Path(root)
    protocol = _load_json(root / "pilot/pilot-protocol.json")
    time_model = _load_json(root / "roadmap/time-model.json")
    compiled = validate_pilot_protocol(protocol, time_model)
    return {
        "schemaVersion": 1,
        "protocolVersion": compiled["protocolVersion"],
        "protocolFingerprint": compiled["protocolFingerprint"],
        "toolVersion": compiled["toolVersion"],
        "timeModelFingerprint": compiled["timeModelFingerprint"],
        "minimumLearnerResponses": 10,
        "learnerWarningRatio": {"numerator": 1, "denominator": 3},
        "learnerPulseItems": compiled["learnerPulseItems"],
        "contextEnums": compiled["contextEnums"],
        "clusters": compiled["clusters"],
        "annualPilot": compiled["annualPilot"],
    }


def render_protocol_js(compiled_contract):
    payload = json.dumps(
        compiled_contract,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )
    return (
        "/* Generated by scripts/build_ium11_cockpit.py; do not edit manually. */\n"
        f"window.IUM11_PROTOCOL = Object.freeze({payload});\n"
    )


def build_cockpit_contract(root, output_path=None):
    root = Path(root)
    output_path = Path(output_path) if output_path is not None else root / DEFAULT_OUTPUT
    rendered = render_protocol_js(compile_cockpit_contract(root))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(
        dir=output_path.parent,
        prefix=f".{output_path.name}.",
        suffix=".tmp",
    )
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as target:
            target.write(rendered)
        os.replace(temporary_name, output_path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise
    return rendered


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    output_path = arguments.output or arguments.root / DEFAULT_OUTPUT
    rendered = render_protocol_js(compile_cockpit_contract(arguments.root))
    if arguments.check:
        if not output_path.is_file() or output_path.read_bytes() != rendered.encode("utf-8"):
            parser.error(f"cockpit contract is not current: {output_path}")
        return 0
    build_cockpit_contract(arguments.root, output_path=output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
