(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.QuestContent=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const sources={
 A:{id:'A',kind:'Klassenchat',title:'Habt ihr das schon gehört?',author:'Mila, Klasse 5b',date:'23. September 2026 · 16:10 Uhr',style:'chat',purpose:'Mila gibt eine Nachricht weiter und äußert ihre Sorge.',context:'Übungsquelle · Nachricht an die Klasse',lines:[
 {id:'A1',text:'Jetzt ist es sicher: Ab Montag wird unsere ganze Pausenwiese zum Schulgarten!'},
 {id:'A2',text:'Die Garten-AG hat doch vor den Ferien einen Zettel dazu aufgehängt. Dann können wir da gar nicht mehr spielen!'},
 {id:'A3',text:'Ich habe den Zettel gerade nicht hier. Weiß jemand mehr?'}]},
 B:{id:'B',kind:'Aushang der Garten-AG',title:'Mehr Grün für unsere Schule',author:'Garten-AG der Schule',date:'10. Juni 2026',style:'notice',purpose:'Die AG wirbt für ihren Vorschlag. Sie berichtet noch nicht von einer Entscheidung.',context:'Übungsquelle · Am AG-Brett vor den Sommerferien',lines:[
 {id:'B1',text:'Wir wünschen uns einen Schulgarten auf der ganzen Pausenwiese.'},
 {id:'B2',text:'Dort könnten wir Gemüse und Blumen pflanzen. Wir haben der Schulleitung einen Vorschlag geschickt.'},
 {id:'B3',text:'Noch ist nicht entschieden, ob unser Vorschlag umgesetzt wird.'},
 {id:'B4',text:'Wer bei der Garten-AG mitmachen möchte, kommt mittwochs nach der sechsten Stunde zum AG-Raum. Ideen sind willkommen!'}]},
 C:{id:'C',kind:'Schulmitteilung',title:'Neues von unserer Pausenwiese',author:'Frau Kaya, Schulleiterin',date:'22. September 2026',style:'letter',purpose:'Die Schulleitung erläutert den beschlossenen Versuch und seine Grenzen.',context:'Übungsquelle · Schulwebseite, Mitteilungen an Kinder und Eltern',lines:[
 {id:'C1',text:'Am Montag, 28. September, stellen wir zwei Hochbeete am Rand der Pausenwiese auf.'},
 {id:'C2',text:'Die übrige Wiese bleibt zum Spielen frei.'},
 {id:'C3',text:'Wir probieren den Garten bis Ende November aus. Über einen größeren Garten im nächsten Jahr ist noch nicht entschieden.'},
 {id:'C4',text:'Die Garten-AG kümmert sich um die Pflanzen. Bitte lasst beim Spielen etwas Abstand zu den Beeten.'}]},
 D:{id:'D',kind:'Schulbrief',title:'Unser Sporttag am Freitag',author:'Schulleitung',date:'2. Oktober 2026',style:'letter',purpose:'Die Schule kündigt den ursprünglich geplanten Sporttag an.',context:'Übungsquelle · Brief an die Familien',lines:[
 {id:'D1',text:'Am Freitag, 9. Oktober, findet unser Sporttag auf dem Sportplatz statt.'},
 {id:'D2',text:'Wir beginnen um 8:30 Uhr. Bringt Sportschuhe, eine Trinkflasche und ein Frühstück mit.'}]},
 E:{id:'E',kind:'Klassenchat',title:'Anderer Treffpunkt?',author:'Noah, Klasse 5a',date:'8. Oktober 2026 · 16:05 Uhr',style:'chat',purpose:'Noah gibt eine Änderung weiter und nennt die Mitteilung, auf die er sich stützt.',context:'Übungsquelle · Nachricht an die Klasse',reference:'F',lines:[
 {id:'E1',text:'Morgen ist der Sporttag in der Sporthalle, nicht auf dem Sportplatz. Das steht in der heutigen Mitteilung der Sportleitung.'},
 {id:'E2',text:'Ich habe die Mitteilung hier verlinkt. Weiß jemand auch, wann der Sporttag endet?'}]},
 F:{id:'F',kind:'Mitteilung der Sportleitung',title:'Sporttag am 9. Oktober',author:'Herr Beck, Leiter des Sporttags',date:'8. Oktober 2026 · 14:00 Uhr',style:'notice',purpose:'Die verantwortliche Sportleitung teilt eine Änderung zum selben Sporttag mit.',context:'Übungsquelle · Schulwebseite, Bereich Sport; Ziel des Verweises aus dem Chat',lines:[
 {id:'F1',text:'Wegen des angekündigten starken Regens verlegen wir den Sporttag am Freitag, 9. Oktober, vom Sportplatz in die Sporthalle.'},
 {id:'F2',text:'Der Beginn bleibt bei 8:30 Uhr. Bringt bitte saubere Hallenschuhe mit.'}]}
};
const verdicts=[{id:'belegt',label:'Belegt',meaning:'Eine passende Stelle stützt die Aussage.'},{id:'widerlegt',label:'Widerlegt',meaning:'Eine passende Stelle sagt das Gegenteil.'},{id:'offen',label:'Offen',meaning:'Mit diesen Quellen noch nicht zu entscheiden.'}];
const claims=[
 {id:'wiese',text:'Ab Montag wird die ganze Pausenwiese zum Garten.',answer:'widerlegt',evidence:['C2'],hint:'Achte auf „ganze“ und „ab Montag“. Suche eine Aussage darüber, was tatsächlich mit der Fläche passiert.',feedback:'C2 sagt ausdrücklich: Die übrige Wiese bleibt zum Spielen frei. Der Wunsch der AG ist kein Beleg für einen Beschluss.'},
 {id:'zukunft',text:'Im nächsten Jahr wird der Garten größer.',answer:'offen',evidence:['C3'],hint:'Suche eine Angabe zur Zukunft. Ist die Entscheidung schon gefallen? „Nein“ und „noch nicht entschieden“ bedeuten etwas anderes.',feedback:'C3 sagt, dass darüber noch nicht entschieden ist. Das heißt weder „Ja“ noch „Nein“. Die Entscheidung bleibt offen.'},
 {id:'beete',text:'Am Montag werden zwei Hochbeete aufgestellt.',answer:'belegt',evidence:['C1'],extra:true,hint:'Vergleiche Zeitpunkt und Anzahl in der Aussage mit der Mitteilung.',feedback:'C1 nennt Montag, den 28. September, und zwei Hochbeete. Die Stelle stützt beide Teile der Aussage.'},
 {id:'wunsch',text:'Im Juni wünschte sich die Garten-AG einen Garten auf der ganzen Wiese.',answer:'belegt',evidence:['B1'],extra:true,hint:'Hier geht es um einen damaligen Wunsch. Welche Personengruppe kann ihren eigenen Wunsch beschreiben?',feedback:'B1 belegt den damaligen Wunsch der AG. Für diese Frage ist der ältere Aushang die passende Quelle.'}
];
const transfer=[
 {id:'ort',text:'Der Sporttag findet auf dem Sportplatz statt.',answer:'widerlegt',evidence:['F1'],hint:'Beziehen sich die Texte auf denselben Sporttag? Prüfe, ob eine Mitteilung den bisherigen Plan verändert.',feedback:'F1 verlegt den Sporttag am 9. Oktober wegen Regen in die Halle. Der alte Schulbrief D1 zeigt den früheren Plan. Er ist für den Treffpunkt überholt.'},
 {id:'chat',text:'Noahs Nachricht nennt den richtigen neuen Ort.',answer:'belegt',evidence:['F1'],hint:'Folge Noahs Verweis. Welche ursprüngliche Mitteilung kann seine Nachricht bestätigen?',feedback:'Die Mitteilung der verantwortlichen Sportleitung bestätigt die Halle in F1. Noah gibt die Änderung richtig weiter. E1 allein wäre nur eine Wiederholung seiner Behauptung.'},
 {id:'ende',text:'Der Sporttag endet um 12 Uhr.',answer:'offen',evidence:['none'],hint:'Suche nach einer Endzeit. Ein Beginn verrät noch nicht, wann eine Veranstaltung endet.',feedback:'Die Quellen nennen den Beginn, aber keine Endzeit. 12 Uhr ist damit weder belegt noch widerlegt. Frage die Sportleitung oder suche eine Mitteilung mit dieser Angabe.'}
];
const sourceQuestions=[
 {id:'beschluss',question:'Was soll am kommenden Montag passieren? Welche Quelle hilft dir am direktesten?',answer:'C',hint:'Wer berichtet von einem beschlossenen Vorgehen und nennt den passenden Zeitpunkt?',feedback:'C erläutert den beschlossenen Versuch. Inhalt, Datum und Zuständigkeit passen zur Frage. Allein die offizielle Gestaltung wäre kein Beleg.'},
 {id:'wunsch',question:'Was wollte die Garten-AG im Juni?',answer:'B',hint:'Suche die Äußerung der AG aus diesem Zeitraum.',feedback:'B stammt von der AG und nennt ihren damaligen Wunsch. Für diese Frage ist gerade die ältere Quelle passend.'}
];
const modelExample={title:'Einmal gemeinsam prüfen',source:'Fundbüro · Frau Sommer, Schulsekretariat · 21. September',text:'Am Dienstag ist das Fundbüro von 10 bis 11 Uhr geschlossen. Ab 11 Uhr könnt ihr wieder verlorene Sachen abholen.',claim:'Das Fundbüro ist am Dienstag den ganzen Tag geschlossen.',steps:[
 ['Die Frage genau lesen','Es geht um Dienstag und den ganzen Tag.'],
 ['Eine passende Quelle finden','Das Schulsekretariat betreut das Fundbüro und informiert über seine Öffnungszeiten.'],
 ['Die entscheidende Stelle lesen','„Ab 11 Uhr könnt ihr wieder verlorene Sachen abholen.“'],
 ['Den Schluss erklären','Die Aussage ist widerlegt: Ab 11 Uhr ist das Abholen möglich. Also ist das Fundbüro nicht den ganzen Tag geschlossen.']
]};
const steps=[
 {id:'auftrag',short:'Auftrag',title:'Was wird aus unserer Pausenwiese?',goal:'Erst vermuten. Dann gezielt nachsehen.',task:'Eine Nachricht sorgt für Unruhe. Finde heraus, was dahintersteckt – und antworte deiner Klasse mit Belegen.',sources:['A'],time:5,
 knowledge:'Eine Behauptung ist eine Aussage, die jemand für richtig hält. Ein erster Eindruck ist noch kein geprüftes Ergebnis.',hint:'Welche Wörter machen Milas Nachricht besonders weitreichend?',help:'Achte auf „ganze“ und „ab Montag“. Du kannst vermuten, ohne dich schon festzulegen. Frage dich, welche Information dir noch fehlt.',outcome:'Eine erste Einschätzung und eine Frage, die du untersuchen willst.',expected:'Ich bin noch unsicher: Mila nennt einen alten Zettel, aber keinen aktuellen Beschluss. Ich möchte prüfen, ob ab Montag wirklich die ganze Wiese zum Garten wird.',teacher:'Zeigen Sie zunächst nur den Chat. Lassen Sie eine vorläufige Einschätzung und eine Prüffrage formulieren. Es gibt hier keine bewertete Wahrheitsabstimmung.',criteria:['Vermutung und geprüftes Ergebnis werden unterschieden.','Die Prüffrage bezieht sich auf die Fläche und den Zeitpunkt.']},
 {id:'quellen',short:'Quellen',title:'Wie gehst du einer Nachricht nach?',goal:'Du lernst ein Vorgehen und wählst Quellen passend zur Frage.',task:'Schau dir zuerst an, wie eine Behauptung geprüft wird. Untersuche danach die drei Dokumente zur Pausenwiese.',sources:['A','B','C'],time:12,
 knowledge:'Frage: Wer hat das geschrieben? Wann? Wozu? Woher kann die Person das wissen? Die Quelle muss zu deiner konkreten Frage passen.',hint:'Ein Vorschlag beschreibt einen Wunsch. Eine spätere Mitteilung kann berichten, was daraus geworden ist.',help:'Lies bei jedem Dokument Herkunft, Datum und Text zusammen. Die AG kann ihren Wunsch erklären; für den aktuellen Stand brauchst du eine passende Mitteilung.',outcome:'Du kannst erklären, welche Quelle zu welcher Frage passt.',expected:'Für den aktuellen Stand nutze ich C: Die Schulleitung erläutert den Versuch im September. Für den Wunsch im Juni nutze ich B von der Garten-AG. Milas Chat zeigt ihre Behauptung, aber noch keinen Beschluss.',teacher:'Sie können das Fundbüro-Beispiel selbst laut denkend erklären. Quellen A–C lassen sich danach gemeinsam lesen oder von den Kindern untersuchen. Anschließend ist der Direkteinstieg bei „Belege“ möglich.',criteria:['Die Quellenwahl wird aus Frage und Inhalt begründet.','Datum und Zuständigkeit werden berücksichtigt, ohne daraus eine allgemeine Rangliste zu machen.']},
 {id:'belege',short:'Belege',title:'Was trägt dein Urteil?',goal:'Verbinde eine Aussage mit einer passenden Stelle im Dokument.',task:'Prüfe die zwei Kernfragen. Wähle eine Textstelle direkt in der Quelle und entscheide: belegt, widerlegt oder offen?',sources:['A','B','C'],time:15,
 knowledge:'„Widerlegt“ braucht einen Gegenbeleg. „Offen“ bedeutet: Mit diesen Quellen kannst du noch nicht entscheiden. Auch eine ausdrücklich offene Entscheidung ist eine wichtige Angabe.',hint:'Lies den ganzen Satz. Passt er genau zu der Aussage, die du gerade prüfst?',help:'Wunsch und Entscheidung sind verschieden. Prüfe außerdem, ob der Satz die Gegenwart oder das nächste Jahr betrifft.',outcome:'Zwei begründete Urteile. Erkläre einen Zusammenhang in eigenen Worten.',expected:'Ganze Wiese ab Montag: widerlegt durch C2. Größerer Garten im nächsten Jahr: offen, C3. Zusatz: zwei Beete belegt durch C1; Wunsch im Juni belegt durch B1.',teacher:'Lassen Sie ein Kind eine konkrete Stelle zeigen und den Zusammenhang erklären. Richtige Auswahl allein ist kein ausreichender Lernnachweis. Die zwei zusätzlichen Aussagen dienen bei Bedarf der Vertiefung.',criteria:['Die gewählte Textstelle trägt das Urteil.','Offene Zukunft und ausdrücklicher Gegenbeleg werden unterschieden.','Eine Begründung verbindet Aussage und Text in eigenen Worten.']},
 {id:'antwort',short:'Antwort',title:'Aus Belegen wird eine Antwort.',goal:'Schreibe sachlich. Zeige, worauf du dich stützt.',task:'Antworte Mila in drei bis vier Sätzen. Nutze deine Belege und sage auch, was noch offen ist.',sources:['A','B','C'],time:15,
 knowledge:'Eine prüfbare Antwort nennt Ergebnis, Quelle und genaue Textstelle. Erkläre, was die Stelle für die Behauptung bedeutet.',hint:'Kann ein anderes Kind mit deinen Angaben nachvollziehen, woher du das weißt?',help:'Nutze bei Bedarf: „Laut … vom …“ / „In … steht …“ / „Deshalb …“ / „Noch offen ist …“. Formuliere zuerst mündlich, wenn dir das hilft.',outcome:'Eine Antwort mit Belegen und eine begründete Überarbeitung.',expected:'Nicht die ganze Wiese wird zum Garten. Laut Schulmitteilung vom 22. September entstehen zwei Hochbeete; die übrige Wiese bleibt zum Spielen frei (C1/C2). Der Aushang der AG beschrieb einen Wunsch. Ob der Garten nächstes Jahr größer wird, ist noch offen (C3).',teacher:'Vergleichen Sie die fast passende und die genaue Begründung. Lassen Sie Quelle, Textstelle und Schluss markieren. Für den Direkteinstieg stehen alle Quellen und Kriterien auch ohne frühere Eingaben bereit.',criteria:['Quelle und genaue Stelle werden genannt.','Der Schluss aus dem Beleg wird erklärt.','Die offene Entscheidung wird benannt.','Eine Überarbeitung oder Beibehaltung wird begründet; Mila wird sachlich angesprochen.']},
 {id:'transfer',short:'Neuer Fall',title:'Sportplatz oder Sporthalle?',goal:'Prüfe einen neuen Fall. Entscheide mit Belegen.',task:'Am Freitag ist Sporttag. Der Schulbrief und Noahs Chat nennen verschiedene Orte. Wo sollst du hin?',sources:['D','E','F'],time:12,
 knowledge:'Verfolge eine Nachricht bis zur ursprünglichen Mitteilung. Prüfe, ob sich eine Änderung wirklich auf dasselbe Ereignis bezieht.',hint:'Noah nennt eine Mitteilung. Folge seinem Verweis und vergleiche sie mit dem Schulbrief.',help:'Vergleiche Ereignis, Datum und Begründung der Änderung. Der ältere Brief kann einen früheren Plan richtig beschreiben, der inzwischen geändert wurde.',outcome:'Eine Antwort mit ursprünglichem Beleg und einer noch offenen Frage.',expected:'Ich gehe in die Sporthalle. Die Sportleitung verlegt in F1 denselben Sporttag am 9. Oktober wegen Regen dorthin. Noah gibt diese Änderung korrekt weiter; der ältere Schulbrief nennt den überholten Plan. Eine Endzeit fehlt. Dafür muss ich die Sportleitung fragen oder eine weitere Mitteilung finden.',teacher:'Lassen Sie zunächst individuell prüfen. Geben Sie die Aktualisierung nicht vorab als richtige Quelle vor. Besprechen Sie anschließend, warum hier der Chat zutrifft und der alte Schulbrief nicht mehr den aktuellen Ort nennt.',criteria:['Die Änderung wird über F1 zum selben Sporttag belegt.','Eine Chatnachricht wird nicht pauschal abgewertet.','Die fehlende Endzeit bleibt offen; ein sinnvoller nächster Prüfschritt wird genannt.']}
];
return {sources,steps,claims,transfer,verdicts,sourceQuestions,modelExample};
});
