'use strict';
const P=require('./studio-learning.js'),S=require('./studio-model.js');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dirs=['oben','rechts','unten','links'],arrows=['↑','→','↓','←'];
function start(l){
 if(!l.room)return '<p><b>Modell:</b> Drei Werkstücke im Vorrat, ein freier Platz in der Prüfstation.</p>';
 const {width:w,height:h,start:p}=l.room,clean=new Set([...(l.prior||[]),p.slice(0,2).join()]);
 return `<div class="lesson-start"><div class="mini-floor" role="img" aria-label="Start: Spalte ${p[0]}, Reihe ${p[1]}, Blick ${dirs[p[2]]}" style="--cols:${w};--rows:${h}"><div class="mini-tiles">${Array.from({length:h},(_,y)=>Array.from({length:w},(_,x)=>`<span class="mini-tile ${clean.has((x+1)+','+(y+1))?'clean':''}"><small>${x+1},${y+1}</small>${p[0]===x+1&&p[1]===y+1?'<b>'+arrows[p[2]]+'</b>':''}</span>`).join('')).join('')}</div></div><p><b>Start:</b> ${w} Spalten, ${h} Reihen.<br>Spalte ${p[0]}, Reihe ${p[1]}, Blick ${dirs[p[2]]}.<br>${clean.size} Kachel${clean.size===1?' ist':'n sind'} bereits sauber.<br>Reihen werden von oben gezählt.</p></div>`;
}
function programs(l){return l.station?'<pre>Plan A: wiederhole 3 [aufnehmen; prüfen; ablegen]\n\nPlan B: wiederhole 3 [aufnehmen]\n        wiederhole 3 [prüfen]\n        wiederhole 3 [ablegen]</pre>':l.code?'<pre>'+esc(l.code)+'</pre>':'<p>Eigener Plan: zunächst leer.</p>';}
function ways(){return `<section id="wege" class="guide-section"><p class="eyebrow">Vertiefung · mehrere Lösungen</p><h2>Ein Boden, zwei gültige Wege</h2><p>Beide Pläne beginnen links unten mit Blick nach rechts. Sie reinigen denselben Boden mit vier Spalten und drei Reihen.</p><div class="two-plans"><div><h3>Reihe für Reihe</h3><pre>${esc(P.examples.rows)}</pre><p>Drei Fahrten reinigen jeweils den Rest einer Reihe. Am rechten Rand führt links – vor – links in die nächste Reihe. Am linken Rand passt rechts – vor – rechts. So werden zuerst die untere, dann die mittlere und zuletzt die obere Reihe sauber.</p></div><div><h3>Spalte für Spalte</h3><pre>${esc(P.examples.columns)}</pre><p>Die erste Linksdrehung zeigt nach oben. Zwei Fahrten reinigen den Rest der ersten Spalte. Oben führt rechts – vor – rechts nach rechts in die nächste Spalte, mit Blick nach unten. Unten führt links – vor – links in die nächste Spalte, mit Blick nach oben. Wiederhole dieses Wechseln bis zur vierten Spalte.</p></div></div><h3>Vergleiche selbst</h3><p>Zähle Fahrten und Drehungen beider Pläne. Erkläre, warum beide alle zwölf Kacheln erreichen. Ist weniger geschriebener Code immer ein kürzerer Weg?</p><details><summary>Vergleich auflösen</summary><p>Beide Pläne haben elf Fahrten. Der Reihenweg braucht zusätzlich vier Drehungen: insgesamt 15 Aktionen. Der Spaltenweg braucht sieben Drehungen: insgesamt 18 Aktionen. Beide erfüllen den Auftrag. Eine Schleife verkürzt die Schreibweise, aber nicht die ausgeführten Fahrten und Drehungen.</p></details><a class="button-link" href="index.html#own">Zur eigenen Planung</a></section>`;}
function render(teacher=false){
 const title=teacher?'Unterrichten mit dem Lernstudio':'Wissen: Schleifen und Teilpläne';
 return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>${title} | IuM</title><link rel="stylesheet" href="studio.css"><link rel="stylesheet" href="prototype.css"></head><body class="guide-page"><a class="skip" href="#main">Zum Inhalt</a><header class="topbar"><a class="brand" href="index.html">↳ Lernstudio</a><nav class="top-actions"><a href="${teacher?'wissen':'lehrkraft'}.html">${teacher?'Wissen für Lernende':'Für Lehrpersonen'}</a><a href="index.html">Zum Experiment</a></nav></header><main id="main"><p class="eyebrow">IuM · Klasse 5 · Sauber geplant</p><h1>${title}</h1><p class="lead">${teacher?'Sie können jede Erklärung selbst übernehmen und danach einzelne Übungen öffnen. Diese Übersicht enthält die nötigen Startbilder, Programme, Gesprächsimpulse und fachlichen Antworten. Sie funktioniert auch ohne die Simulation.':'Hier findest du Erklärungen, Startbilder und Beispiele. Du kannst jederzeit eine einzelne Station nachlesen. Klappe eine Lösung erst auf, wenn du selbst überlegt hast.'}</p>
 ${teacher?'<section class="guide-section"><h2>Frei kombinieren</h2><p><b>Selbstständig:</b> Merksatz lesen, vermuten oder planen, den Versuch untersuchen und mit den Erklärungskriterien vergleichen. Hinweise und Lösungen helfen bei Bedarf. Nicht alle Kinder müssen jede Zusatzfrage bearbeiten.</p><p><b>Im Unterrichtsgespräch:</b> Eine Station auswählen, Bild und Befehle an der Tafel oder mit Karten darstellen, Vorhersagen begründen lassen. Anschließend direkt die zugehörige Übung oder einen weiterführenden Planungsauftrag öffnen.</p><p><b>Im Lehrvortrag:</b> Den fachlichen Kern am vorbereiteten Beispiel erklären. Nach einem oder zwei Befehlen eine Vorhersagepause einlegen. Als Anschluss eigene Fehlerkorrekturen oder Pläne bearbeiten lassen.</p><p><b>Mögliche Ausschnitte:</b> Grundbefehle: Station 1. Schleifen: 2–4. Teilpläne und eigener Algorithmus: 5–8. Behauptung und Transfer: 9–10. Späterer Abruf: 11. Es gibt keine gesperrten Stationen und keinen vorausgesetzten digitalen Abschluss.</p><p><b>Lernnachweis:</b> Ausgeführter Plan und begründete Erklärung. Die Zusatzfragen sind kurze Selbstkontrollen. Die Oberfläche weist keine automatisch bestätigte Gesamtkompetenz aus.</p></section>':''}
 <nav class="guide-nav" aria-label="Stationen">${S.order.map((id,i)=>`<a href="#${id}">${i+1}. ${P.lesson(id).short}</a>`).join('')}<a href="#wege">Zwei gültige Wege</a><a href="#begriffe">Begriffe</a></nav>
 ${S.order.map((id,i)=>{const l=P.lesson(id);return `<section class="guide-section" id="${id}"><p class="eyebrow">Station ${i+1} · ${l.group}</p><h2>${l.title}</h2><p>${l.entry}</p><p class="core-sentence"><b>Merke</b> ${l.core}</p>${start(l)}${programs(l)}${teacher?`<h3>So können Sie es erklären</h3><p>${l.teach}</p><h3>Gesprächsimpuls</h3><p>${l.discuss}</p>`:''}<article>${l.explain}</article><h3>${teacher?'Anschlussauftrag':'Dein Auftrag'}</h3><p>${l.task}</p><h3>Eine gute Erklärung zeigt</h3><ul>${l.criteria.map(x=>'<li>'+x+'</li>').join('')}</ul><p><b>Satzanfang:</b> ${l.prompt}</p>${teacher?'<div class="answer"><h3>Fachliche Antwort / mögliche Lösung</h3><pre>'+esc(l.solution)+'</pre></div>':'<details><summary>Eine Lösung nachvollziehen</summary><pre>'+esc(l.solution)+'</pre></details>'}<a class="button-link" href="index.html#${id}">Station ${i+1} direkt öffnen →</a></section>`;}).join('')}
 ${ways()}<section class="guide-section" id="begriffe"><h2>Die wichtigen Begriffe</h2><p><b>Befehl / Anweisung:</b> Ein genauer Auftrag, zum Beispiel vor oder links.</p><p><b>Programm:</b> Ein Plan in einer Schreibweise, die unsere Simulation ausführen kann.</p><p><b>Algorithmus:</b> Ein genauer Plan aus geordneten Anweisungen, mit dem du ein Problem löst.</p><p><b>Schleife:</b> Sie wiederholt eine Gruppe von Befehlen. Die Zahl gibt an, wie oft.</p><p><b>Schleifenkörper:</b> Alle Befehle innerhalb der Klammer. Ein Durchlauf führt diesen Körper einmal ganz aus.</p><p><b>Teilplan:</b> Ein Stück des ganzen Plans, etwa eine gerade Fahrt oder ein Übergang.</p><p><b>Zustand:</b> Wie es gerade steht: beim Roboter seine Kachel und sein Blick, bei der Prüfstation zum Beispiel frei oder belegt.</p><h3>Was unser Modell kann</h3><p>Der Boden besteht aus Kacheln. Eine erreichte Kachel gilt als sauber. Drehen reinigt keine neue Kachel. Der Roboter erkennt keine Hindernisse und sucht keinen Weg. Am Rand stoppt er. Eine echte Maschine kann anders gebaut sein und zum Beispiel Sensoren besitzen.</p></section></main></body></html>`;
}
module.exports={render,start,programs,ways};
